### ISSUE TITLE
alternative output formats (html, txt)?

### ISSUE THREAD

**Issue by blalovic** [Merck/r2rtf#10]
Thank you for an excellent package!  This is a request for support of other output formats, such as html for integration with rmarkdown.

**Comment by elong0527** [comment]
This packages intend to be light weighted and focus on RTF output. 

For txt, please try https://cran.r-project.org/web/packages/unrtf/index.html or https://github.com/Roche/rtables
For html, please try https://github.com/rstudio/gt or xtable, DT etc.
