### ISSUE TITLE
Requests that left and right page header text be displayed in the same line

### ISSUE THREAD

**Issue by kaipingyang** [Merck/r2rtf#104]
When I tried to create a left page header and a right page header using the rtf_page_header() function, I found that rtf_page_header could not make both page header text on the same line. Such as:
```
library(tidyverse)
library(r2rtf)
table <- tibble(
  label=c('Age (years)',' n',' Mean (SD)',' Median',' Q1, Q3',' Min, Max'),
  Total=c('','997','59.3 (11.14)','61.0','53, 67','23, 86'))

table %>% 
  rtf_page_header(
    text = c("Protocol XXX-XXX-XXX","Page \\pagenumber of \\pagefield"),
    text_justification = c("l","r"),
    text_format=rep("b",2)
  ) %>%
  rtf_body(
    col_rel_width = c(3, 3),
    text_justification = c("l", "c"),
  ) %>% 
  rtf_encode() %>%
  r2rtf::write_rtf("test.rtf")
```
But in practice, we often need to display multiple page header text on the same line, please add this feature.

Best wishes!

**Comment by elong0527** [comment]
The r2rtf logic is one line per element. 

One (adhoc) way is to add necessary white space in your text. i.e. 

```
    n_space = 20 # modify it as needed. 
    
    text = paste(c("Protocol XXX-XXX-XXX",  rep(" ", n_space),  "Page \\pagenumber of \\pagefield"))

    text_justification = c("l"),
```

Please share a RTF file created by other R or SAS tool that can achieve this goal. So we can explore the RTF syntax to achieve this goal if possible.

**Comment by meeeeeeeeo** [comment]
Here is a example:
The r2rtf code:
```
data.frame(x = '123', y = 'abc') %>% 
  rtf_page_header(
    text = c('aaaa', 'bbbb', 'Page \\pagenumber of \\pagefield'),
    text_justification = c('l', 'c', 'r')
  ) %>% 
  rtf_body() %>% 
  rtf_encode() %>% 
  write_rtf(str_glue("{task_folder}/dev/reports/tables/test.rtf"))
```
it generate the rtf (header) code, and the header located at three different line:
```
{\header
{\pard\sb15\sa15\fi0\li0\ri0\ql\fs24{\f0 aaaa}\par}
{\pard\sb15\sa15\fi0\li0\ri0\qc\fs24{\f0 bbbb}\par}
{\pard\sb15\sa15\fi0\li0\ri0\qr\fs24{\f0 Page \chpgn  of {\field{\*\fldinst NUMPAGES }} }\par}
}
```
replace this part of rtf code as belowing, and it display the header at one line
```
{\header{
\pard\sb15\sa15\fi0\li0\ri0\ql\fs24{\f0 aaaa\cell}\cellx3000
\pard\sb15\sa15\fi0\li0\ri0\qc\fs24{\f0 bbbb\cell}\cellx6000
\pard\sb15\sa15\fi0\li0\ri0\qr\fs24{\f0 Page \chpgn  of {\field{\*\fldinst NUMPAGES }} \cell}\cellx9000
{\row}
}}
```
the number of `\cellx3000` should depends on the paper weight.

**Comment by elong0527** [comment]
Thanks for the examples. 

From design perspective, it will require `rtf_page_header` to understand both `vector` and `data.frame` as input to achieve full flexibility.

Alternatively, another function `rtf_page_header_table`  can be created to achieve the goal. 

cc: @nanxstats

**Comment by nanxstats** [comment]
I agree. It would be better to handle this in a new function, instead of expanding the acceptable input data types (open-closed principle). If so, I guess `rtf_page_footer()` should also have an equivalent.

**Comment by elong0527** [comment]
Close, as no current plan to implement this function
