### ISSUE TITLE
Ask for add table theme

### ISSUE THREAD

**Issue by kaipingyang** [Merck/r2rtf#105]
In practice, we often use three-line table. To do this, I need to set the three-line table with parameters from rtf_page，rtf_colheader，rtf_body, as follows:
```
library(tidyverse)
library(r2rtf)

table <- tibble(
  label=c('Age (years)',' n',' Mean (SD)',' Median',' Q1, Q3',' Min, Max'),
  Total=c('','997','59.3 (11.14)','61.0','53, 67','23, 86'))

table %>% 
  rtf_page(
    orientation = "landscape",
    border_first = "single",
    border_last = "single",
  ) %>%
  rtf_colheader(
    " | Total",
    col_rel_width = c(3, 3),
    border_left = NULL,
    border_right = NULL,
    text_format=rep("b",2)
  ) %>%
  rtf_body(
    col_rel_width = c(3, 3),
    border_left = NULL,
    border_right = NULL,
    text_justification = c("l", "c")
  ) %>% 
  rtf_encode() %>%
  r2rtf::write_rtf("test.rtf")
```
It would be nice if the r2rtf package could add functions like rtf_theme() to set various table theme styles such as three-line table.

Best wishes!

**Comment by elong0527** [comment]
The `theme` feature is nice yet beyond the current scope of `r2rtf`. 

You can define your default values in two general approaches. 

1. define defaults using `default` package https://github.com/goldingn/default
2. wrap up `r2rtf` exported functions with your desired default value in an R package.

**Comment by kaipingyang** [comment]
Sounds good! I'll try both of your suggestions.
