### ISSUE TITLE
Enhanced paging

### ISSUE THREAD

**Issue by kaipingyang** [Merck/r2rtf#107]
Sometimes the variable label of a block in an rtf table will be broken due to pagination. As shown in the figure below.

![page_issue](https://user-images.githubusercontent.com/55199277/175852801-e88c2ba8-94bb-48e2-8706-deefcc1041c0.png)

I tried using the page_by and new_page arguments of the rtf_body function. But this seems to be designed for intext tables. 

```
library(tidyverse)
library(r2rtf)

test <- tibble(
  label=c('Age (years)',' n',' Mean (SD)',' Median',' Q1, Q3',' Min, Max') %>% rep(4),
  Total=c('','997','59.3 (11.14)','61.0','53, 67','23, 86') %>% rep(4),
  page = rep(1:2,each=12)
  )

test %>% 
  rtf_page(
    orientation = "landscape",
    border_first = "single",
    border_last = "single"
  ) %>% 
  rtf_title(
    "Test table",
    text_format="b"
  ) %>%
  rtf_colheader(
    " | Total",
    col_rel_width = c(3, 3),
    border_left = NULL,
    border_right = NULL,
    text_format=rep("b",2)
  ) %>% 
  rtf_body(
    page_by = "page",
    new_page =TRUE,
    col_rel_width = c(3, 3, 3),
    text_justification = c("l", "c", "c"),
    text_color =c("black","black","white"),
    border_top = NULL,
    border_left = NULL,
    border_right = NULL,
    border_bottom = NULL
  ) %>% 
  rtf_encode() %>%
  r2rtf::write_rtf("test.rtf")
```

I used the code above. The page_by argument starts with a separate line as the head for each group, which is great for intext tables. However, it seemed inconvenient for the appendix table, so I had to set the color of "page" to white. So far I can only make the following effect:
![test](https://user-images.githubusercontent.com/55199277/175853833-e8f32fea-91ae-41d5-b2cf-b53436fd9381.png)

Could r2rtf design paging parameters for appendix table?
Such as:
Add the display argument to rtf_body to select which columns of the dataframe the body displays;
Add the page_var parameter to rtf_body only as an auxiliary variable for paging. But we don't start a separate line as the header for each group, as the page_by parameter does.
```
rtf_body (
  display = c("label","total"),
  page_var = "page"
)
```

Table for appendix allows multiple blocks on a page, but does not want any block to be paginated. The final output we are expecting is as follows:
![test_page](https://user-images.githubusercontent.com/55199277/175855948-cb470a0d-bfc2-48e8-a93b-74af03a8ee2c.png)

**Comment by kaipingyang** [comment]
Thanks for your suggestion, I will try to create pagination by combination.
It sounds good for a combination of group_by, new_page and pageby_row in rtf_body!

The final output we are expecting is the last picture in the description of the question and I have just revised the typesetting.

Look forward to:   
for the following Tibble:  
```
test <- tibble(
  label=c('Age (years)',' n',' Mean (SD)',' Median',' Q1, Q3',' Min, Max') %>% rep(4),
  total=c('','997','59.3 (11.14)','61.0','53, 67','23, 86') %>% rep(4),
  page = rep(1:2,each=12)
  )
```
Arguments like the following can be used:  
```
rtf_body(
  display = c("label","total"),
  page_var = "page"
)
```
The following rtf output are reported(block2 is not broken by pagination): 
![page_expecting](https://user-images.githubusercontent.com/55199277/176085425-f3d2989b-8b6c-4c5e-9078-7b15b644cd72.png)

**Comment by kaipingyang** [comment]
Thanks for your suggestion on a combination of group_by, new_page and pageby_row in rtf_body!

I tried the following parameters in rtf_body :
```
rtf_body(
    page_by = "page",
    new_page =TRUE,
    pageby_row = "first_row"
)
```


After setting the border of each module of the rtf table, I succeeded in obtaining a three-line table that blocks cannot be broken by pagination. Here is my code and the output:

code:
```
test %>% 
  rtf_page(
    orientation = "landscape",
    border_first = "single",
    border_last = "single"
  ) %>% 
  rtf_title(
    "Test table",
    text_format="b"
  ) %>%
  rtf_colheader(
    " | Total",
    col_rel_width = c(3, 3),
    border_left = NULL,
    border_right = NULL,
    border_bottom = "single",
    text_format=rep("b",2)
  ) %>% 
  rtf_body(
    page_by = "page",
    new_page =TRUE,
    pageby_row = "first_row",
    col_rel_width = c(3, 3, 3),
    text_justification = c("l", "c", "c"),
    border_left = NULL,
    border_right = NULL,
    # border_top = "single"
  ) %>% 
  rtf_encode() %>%
  r2rtf::write_rtf("test.rtf")
```
output:
![output_page](https://user-images.githubusercontent.com/55199277/176089022-4fa1bdd2-fb78-4e60-9146-b2cb89d3b11f.png)

**Comment by elong0527** [comment]
Cool, good to know it works. 

Closing the ticket
