### ISSUE TITLE
Set table size

### ISSUE THREAD

**Issue by mchastkofsky** [Merck/r2rtf#114]
When generating an rtf file of a table, is there a way to adjust how many rows are on a table per page? It keeps splitting up my results into multiple pages with more than half the page blank. I see ways to adjust column sizes, and cell sizes, but how do I maximize the number of rows on a page to reduce wasted space and excess pages?

**Comment by fb-elong** [comment]
Using `nrow` in `rtf_page`. 

https://merck.github.io/r2rtf/reference/rtf_page.html

Determine proper number of row in each page is a complicated task. While design `r2rtf`, I used a conservative way to avoid overflow.
