### ISSUE TITLE
Questions about blank row and unit of table width

### ISSUE THREAD

**Issue by Rednose22** [Merck/r2rtf#115]
Hi there,

1. How can I delete the blank row when the var_label is null in the baseline characeristics table like screenshot below
![image](https://user-images.githubusercontent.com/69974660/181302031-97f3478a-4dcc-4645-8f32-e04c6888c8fa.png)

2. What's the unit of table and column width in the rtf_page/rtf_body function?

Many thanks.

**Comment by elong0527** [comment]
1. The value of `var_label` should be `-----`. Please refer example in https://merck.github.io/r2rtf/articles/example-sublineby-pageby-groupby.html?q=-----#example-1-pageby

2. depends on which argument you are referring to. It should be documented in each variable argument. If you find any function argument is missing the information, please let us know.
