### ISSUE TITLE
Split the page for specific section of table

### ISSUE THREAD

**Issue by Rednose22** [Merck/r2rtf#116]
Hi there, I'd like to ask when the table is over 1 page, how to control which section of table could be displayed in the first page of table. 
1. For example, as screenshot below, the BMI section spread in two pages then normally we will try to move the whole section to the next page.
![image](https://user-images.githubusercontent.com/69974660/182121693-5724ca8a-d600-44d9-861c-cd64909642e7.png)
![image](https://user-images.githubusercontent.com/69974660/182121765-02c2e29c-1028-4a62-9e67-63f477345744.png)

Thanks.

**Comment by elong0527** [comment]
Currently `r2rtf` support either using all rows defined by `nrow` argument in `rtf_page` or split one section per page. 

Please refer the `page_by` and `new_page` argument. 

example: https://merck.github.io/r2rtf/articles/r2rtf.html#page_by-feature
