### ISSUE TITLE
rtf_enode fails when data contains NA and fixed-width font is used

### ISSUE THREAD

**Issue by lzeitlin** [Merck/r2rtf#118]
When the input data includes NA values and a fixed font (e.g. text_font=9) is used, rtf_encode fails with the message: 

Error in if (any(index)) { : missing value where TRUE/FALSE needed

Example code:

library(tidyverse)
library(r2rtf)
df <- tibble(col = c("A", NA, "B"))
df %>% rtf_body(text_font = 9) %>% rtf_encode()

**Comment by riawoo** [comment]
I have the exact same problem. How do I solve this problem?

**Comment by elong0527** [comment]
Could you provide a reproduce example and your package version?

**Comment by riawoo** [comment]
Please refer to issue 146
