### ISSUE TITLE
enable the inclusion of url/hyperlinks in text

### ISSUE THREAD

**Issue by BrianLang** [Merck/r2rtf#126]
Is there a way to enable clickable hyperlinks? We are interested in adding links into the footnotes.

**Comment by elong0527** [comment]
It is relevant to #112.

You may write a helper function to wrap the syntax discussed in 

https://stackoverflow.com/questions/2850575/what-is-the-rtf-syntax-for-a-hyperlink

**Comment by elong0527** [comment]
Closed, as no action item for the ticket
