### ISSUE TITLE
pageby_header as a #byval above the column headers

### ISSUE THREAD

**Issue by Robert-Krajcik** [Merck/r2rtf#13]
I have been asked to find out a way to use the `pageby_header` like a SAS `#byval()` function,
similar to this SAS statement: `title2 "Cohort=#byval(cohort)";`

So instead of showing the `pageby_header` underneath the header created by `rtf_colheader()`
![image](https://user-images.githubusercontent.com/75215958/106669960-70ee1a00-657a-11eb-8e7a-e4cb600323d0.png)

My client wants to see the `pageby_header` as a title line above the header like this:
![image](https://user-images.githubusercontent.com/75215958/106670219-c0344a80-657a-11eb-813c-87eefb0892e6.png)

I know this comes out of the `rtf_body()` function, so adding an option to move it would not be easy to do.
But no matter, I came up with a workaround.

I don't need you to fix anything, @elong0527 , just wanted to share this with you and have you comment on it.

original code:
```{r, eval=FALSE}
sampl_iris <- iris %>% 
  group_by(Species) %>% 
  slice_sample(n = 5) # take 5 rows of each Species

iris_rtf <- sampl_iris %>% 
  rtf_page(orientation = "landscape", 
           nrow = 26,
           border_first = "single", border_last = "single",
           # The value set left, right, top, bottom, header and footer margin in order.
           margin = c(1.0, 1.0, 1.0, 1.0, 0.5, 0.5) ) %>% 
  
  rtf_title( title=paste("\\b\\fs24","Iris data by Species","\\b0"), 
             subtitle = paste("\\fs20","Page \\pagenumber of \\totalpage"),
             text_justification = "l",
             text_convert = TRUE
  ) %>%
  
  rtf_colheader(colheader = c(" Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | "), 
                text_font_size = 9, text_format = "b", 
                col_rel_width = c(2.4,2.4,2.4,2.4,0.1),
                cell_justification = "l",
                text_justification = c(rep("d",4),"l"),
                border_left = "", border_right = ""
  ) %>%
  
  rtf_body(col_rel_width = c(2.4,2.4,2.4,2.4,0.1),
           cell_justification = "l",
           text_justification = c(rep("d",4),"l"),
           text_font_size = 9, text_font = 1,
           page_by = "Species",
           pageby_header = TRUE,
           new_page = TRUE,
           border_first = "single", border_last = "single",
           border_left = "", border_right = "") 

iris_rtf %>% 
  rtf_encode() %>% 
  write_rtf("output/l-iris-before.rtf") 
```

Modified code (using the same data above)
```{r, eval=FALSE}
iris_rtf <- sampl_iris %>% 
  rtf_page(orientation = "landscape", 
           nrow = 26,
           border_first = "single", border_last = "single",
           # The value set left, right, top, bottom, header and footer margin in order.
           margin = c(1.0, 1.0, 1.0, 1.0, 0.5, 0.5) ) %>% 

  rtf_title( title=paste("\\b\\fs24","Iris data by Species","\\b0"), 
             subtitle = paste("\\fs20","Page \\pagenumber of \\totalpage"),
             text_justification = "l",
             text_convert = TRUE
             ) %>%
  
  rtf_subline(text = "subline text", 
              text_font_size = 10, text_font = 9, text_format = "b") %>%
  
  rtf_colheader(colheader = c(" Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | "), 
                text_font_size = 9, text_format = "b", 
                col_rel_width = c(2.4,2.4,2.4,2.4,0.4),
                cell_justification = "l",
                text_justification = c(rep("d",4),"l"),
                border_left = "", border_right = ""
                ) %>%
  
  rtf_body(col_rel_width = c(2.4,2.4,2.4,2.4,0), # 0 for Species suppresses the output
           cell_justification = "l",
           text_justification = c(rep("d",4),"l"),
           text_font_size = 9, text_font = 1,
           page_by = "Species",
           pageby_header = TRUE,
           new_page = TRUE,
           border_first = "single", border_last = "single",
           border_left = "", border_right = "") 

# fix subline indent
attr(attr(iris_rtf, "rtf_subline"),"text_indent_left") <- 0

# get page headers from attributes
by_var <- attr(l_iris, "rtf_pageby")$by_var
# [1] "Species"
eval_this <- paste0('attr(l_iris, "rtf_pageby_row")$',by_var,'$x')
# [1] "attr(l_iris, \"rtf_pageby_row\")$Species$x"
headers <- as.character(eval(parse(text=eval_this)))
# chr [1:3] "setosa" "versicolor" "virginica"

iris_encode <- iris_rtf %>% 
  rtf_encode()

# replace subline text with header line
# note that str_replace only makes one change at a time
for (i in 1:length(headers)) {
  iris_encode$body <- str_replace(iris_encode$body,"subline text",paste("\\\\b",headers[[i]])) 
}

# now write it out
iris_encode %>% 
  write_rtf("output/l-iris-after.rtf") 
```
**I found that setting the `col-rel_width` for the `page_by` variable "Species" to 0 (zero) suppresses the output**
**But the information is still there.**
I was able to extract the "header" information (one per page) like this:
```{r, eval=FALSE}
# get page headers from attributes
by_var <- attr(l_iris, "rtf_pageby")$by_var
# [1] "Species"
eval_this <- paste0('attr(l_iris, "rtf_pageby_row")$',by_var,'$x')
# [1] "attr(l_iris, \"rtf_pageby_row\")$Species$x"
headers <- as.character(eval(parse(text=eval_this)))
# chr [1:3] "setosa" "versicolor" "virginica"
```
and then run `rtf_encode()`
```{r, eval=FALSE}
iris_encode <- iris_rtf %>% 
  rtf_encode()
```
and then replace the "subline text" with the headers.
I'm taking advantage of the fact that `str_replace()` only replaces one string at a time.
Here I'm adding the RTF bold directive in front of the headers.
```{r, eval=FALSE}
# replace subline text with header line
# note that str_replace only makes one change at a time
for (i in 1:length(headers)) {
  iris_encode$body <- str_replace(iris_encode$body,"subline text",paste("\\\\b",headers[[i]])) 
}
```
and then just write it out
```{r, eval=FALSE}
# now write it out
iris_encode %>% 
  write_rtf("output/l-iris-after.rtf") 
```
Thoughts? Comments?

**Comment by elong0527** [comment]
It is a smart way to use `str_replace` for post-processing. 

If the `byval` is outside of table, I assume the whole page shall contain the same `byval`.  

If I need to handle the similar work I would do steps below:

1. create a function to build a table for only one element in `byval` and `byval` will be an argument. 

```
foo_byval <- function(byval)
```

2. split dataset by `byval` and using `lapply` to get a list of encoding object. e.g. call it `encode_list`

3. combine them using the code below

```
 # Combine RTF code
 encode_body <- lapply(encode_list, function(x) x$body)
 encode <- list(start = r2rtf:::as_rtf_init(), 
                 body = paste( unlist(encode_body), collapse = r2rtf:::as_rtf_new_page()), 
                 end = r2rtf:::as_rtf_end())        
  
 encode %>% write_rtf("output.rtf")
```

**Comment by Robert-Krajcik** [comment]
Thanks for your comments, @elong0527  

I will look into updating my code following your suggestions.

**Comment by elong0527** [comment]
I am closing this issue. This feature is beyond the current scope for r2rtf. And there is work around this as suggested.

**Comment by elong0527** [comment]
Will share the progress of #byval feature in next beta version.

**Comment by elong0527** [comment]
A new argument `subline_by` is created in `rtf_body` to allow customized subject line

Please refer example 3 in 

https://merck.github.io/r2rtf/articles/example-sublineby-pageby-groupby.html#example-3-sublineby-pageby-and-groupby-features

**Comment by Robert-Krajcik** [comment]
Thanks @elong0527 !
I am going to test this and let you know how it worked for me.

**Comment by elong0527** [comment]
Excellent! That will be great if you could help us review this Rmd and make suggestions in a pull request.

**Comment by Robert-Krajcik** [comment]
After downloading the development version
> packageVersion("r2rtf")
[1] ‘0.3.0’
I have modified my iris_rtf code above
```{r, eval=FALSE}
library(dplyr)
library(r2rtf)

data("iris")

set.seed(34567)

sampl_iris <- iris %>% 
  group_by(Species) %>% 
  slice_sample(n = 5) %>% # take 5 rows of each Species
  ungroup()

iris_rtf <- sampl_iris %>% 
  arrange(Species) %>% 
  mutate(sublinebytext = paste("\\b Species:",Species)) %>% 
  select(sublinebytext, Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, Species) %>% 
  rtf_page(orientation = "landscape", 
           nrow = 26,
           border_first = "single", border_last = "single",
           # The value set left, right, top, bottom, header and footer margin in order.
           margin = c(1.0, 1.0, 1.0, 1.0, 0.5, 0.5) ) %>% 
  
  rtf_title( title=paste("\\b\\fs24","Iris data by Species","\\b0"), 
             subtitle = paste("\\fs20","Page \\pagenumber of \\totalpage"),
             text_indent_reference = "page_margin",
             text_justification = "l",
             text_convert = TRUE
  ) %>%
  
  rtf_colheader(colheader = c("Sepal.Length |Sepal.Width |Petal.Length |Petal.Width |Species"), 
                text_font_size = 9, text_format = "b", 
                col_rel_width = c(rep(2.4,4),1.0),
                cell_justification = "l",
                text_justification = c(rep("d",4),"r"),
                border_left = "", border_right = "", border_bottom = "single"
  ) %>%
  
  rtf_body(col_rel_width = c(0,rep(2.4,4),1.0),
           cell_justification = "l",
           text_justification = c("l",rep("d",4),"r"),
           text_font_size = 9, text_font = 1,
           subline_by = "sublinebytext",
           border_left = "", border_right = "", border_first = ""
  ) %>% 
  
  rtf_footnote(footnote = "Just a footnote.",
               text_font_size = 9, text_font = 1,
               as_table = FALSE,
               border_bottom = "",
               text_indent_reference = "page_margin")

iris_rtf %>% 
  rtf_encode(page_footnote = "all",
             page_source = "all") %>% 
  write_rtf("output/l-iris-before.rtf") 
```
Seems to work
![image](https://user-images.githubusercontent.com/75215958/118166261-3f93ae80-b3f3-11eb-84ac-0fae2cfe2540.png)

Just getting some warning messages:
1: In graphics::strwidth(x$text, units = "inches", cex = x$cex[1],  :
  font family not found in Windows font database
2: In graphics::strwidth(x$text, units = "inches", cex = x$cex[1],  :
  font family not found in Windows font database
3: In graphics::strwidth(x$text, units = "inches", cex = x$cex[1],  :
  font family not found in Windows font database

Just wondering if you might know what that's about?

**Comment by elong0527** [comment]
Yes, it is about font family defined in 

https://github.com/Merck/r2rtf/blob/3d4903f84dda3b2e5ccf736bfc4fa6a86634794a/R/dictionary.R#L44

To pass R CMD check on github, I did certain modification to align the font family. 

Could you clone the source code and modify `"Times"` to `"Times New Roman"` in line 44? And see if the warning disappeared?  

I will also test from my end on a Windows machine.

**Comment by Robert-Krajcik** [comment]
This worked for me:
`windowsFonts(Times=windowsFont("TT Times New Roman"))`

**Comment by elong0527** [comment]
Exactly, I have fixed it in the new commit. https://github.com/Merck/r2rtf/commit/efb1199b54382a6d26307e11cdc9b434431b3be7

Please re-install and see if it fixed. 

I use `graphics::strwidth` to enhance the calculation of number of rows for long sentences. The downside is that this function depends on OS. (font is a complicated topic...)

**Comment by Robert-Krajcik** [comment]
Yes, that got rid of the warning messages.
Thanks @elong0527 !
