### ISSUE TITLE
Table of contents in Word

### ISSUE THREAD

**Issue by slophaven** [Merck/r2rtf#135]
With the most recent version it is possible to collect individual documents into one file (word or rtf). After having done that one would normally want to create a table of contents in the document. Do you know of an easy way to do that? The titles created with r2rtf are not defined as heading when getting into Word.

**Comment by fb-elong** [comment]
It is possible to handle it within Word. 

1. selecting titles by "Select All Text with Similar Formatting" (It assume the title have different format/style from table bodies. The default setup in r2rtf)

![image](https://user-images.githubusercontent.com/104406613/214652382-e501268b-e7b3-4084-954b-16d25b032a4d.png)

2. define a style for those select text

![image](https://user-images.githubusercontent.com/104406613/214652575-2f6b8e01-c57a-4d74-a5c4-b804929cf85a.png)

3. Create TOC by customize the headings. 

![image](https://user-images.githubusercontent.com/104406613/214652851-01da495c-c807-4df6-be14-5b49769a566a.png)

```
tlf_path <- c(
  "vignettes/rtf/ae_example.rtf", 
  "vignettes/rtf/efficacy_example.rtf"
)

r2rtf::assemble_rtf(
  input = tlf_path,
  output = "rtf-combine.rtf"
)
```
