### ISSUE TITLE
Merging of cells

### ISSUE THREAD

**Issue by BrianLang** [Merck/r2rtf#136]
Hi, we're using r2rtf and would like functionality for the merging of cells. Do you have a recommendation for this?

in particular, we'd be interested in the vertical merging of cells across multiple `rtf_header`, and the horizontal merging of cells in the `rtf_body`. 

The vertical merging seems like more of a problem since it is multiple r2rtf function calls. 
![image](https://user-images.githubusercontent.com/5337833/214000173-e82dda2c-66e5-48d1-9f88-2e345c8b8520.png)

The horizontal merging of cells in a body dataset can be resolved by appending the requisite rtf code into the text of the desired cell.
![image](https://user-images.githubusercontent.com/5337833/214000755-599d7575-f0b3-4d35-b20b-38c40c61c120.png)
 

Is there space in the r2rtf package for this functionality?

**Comment by elong0527** [comment]
For vertical alignment we typically recommend user to pick a row and remove horizontal borders. 

I found a key words in the link below, but need to explore if we can add it in r2rtf. (At least for table header)

https://stackoverflow.com/questions/2781971/merge-cells-vertically-in-rtf

For horizontal merge, I thought r2rtf already have the capability. In your example, which part is difficult to achieve?

Could you provide a code example to show me the best you can achieve?

By comparing with the mock, then highlight what features are missing.

**Comment by fb-elong** [comment]
Below are two example for vertical alignment with an upcoming PR. 

```
# Example 1
tbl |>
  rtf_colheader("a| b | c") |>
  rtf_colheader(" | e | f", 
                border_top = c("", "single", "single"), ) |>
  rtf_body() |>
  rtf_encode() |>
  write_rtf("tmp.rtf")

# Example 2

tbl |>
  rtf_colheader("a| b | c", 
                cell_vertical_justification = c("merge_first", "bottom", "top")) |>
  rtf_colheader(" | e | f", 
                cell_vertical_justification = c("merge_rest", "bottom", "middle")) |>
  rtf_body() |>
  rtf_encode() |>
  write_rtf("tmp.rtf")
  ```
  
  Here are examples for horizontal merge in r4csr book.
  https://r4csr.org/aesummary.html
