### ISSUE TITLE
rtf_body: text font=9 is not accepting

### ISSUE THREAD

**Issue by kalsem** [Merck/r2rtf#152]
Please let us know how to print RTF body with Courier New font, as rtf_body : text_font is not accepting value as 9

**Comment by elong0527** [comment]
I did not see the issue from r2rtf document. Please provide your code and screenshot to explain what's the issue.

https://merck.github.io/r2rtf/articles/rtf-text.html#text-font-type

**Comment by kalsem** [comment]
Thanks.. issue resolved
