### ISSUE TITLE
How do I show table that has 0 number of rows?

### ISSUE THREAD

**Issue by riawoo** [Merck/r2rtf#153]
Just wondering if there is a way to output the table into rtf file, when there are 0 number of rows of data? In other words, just present the header and the wording "No data available in table" below it?

![image](https://user-images.githubusercontent.com/127909758/228717919-1092ce6b-8a36-479e-85ca-93f6cb1b0685.png)

**Comment by BrianLang** [comment]
Hi @riawoo, we typically deal with this by creating a 1x1 data.frame like: `data.frame(x = "No data available in table") and then use that in `rtf_body()`.

**Comment by riawoo** [comment]
Thanks for your response. How do I use the data frame x in rtf_body()? Can you show me an example?

Sorry for the trouble, I am quite new to R.

**Comment by BrianLang** [comment]
We have several worked examples on the package documentation website for example, this one about a baseline table: https://merck.github.io/r2rtf/articles/example-basechar.html

**Comment by elong0527** [comment]
Some pseudo code to illustrate the idea.

```
if(nrow(tbl) == 0){
    tbl <- data.frame(x = "No data available in table")
   
    tbl %>%
        rtf_body(as_colheader = FALSE) %>% 
        rtf_encode() %>% 
        write_rtf("output.rtf")
```

**Comment by riawoo** [comment]
Hi again,

I am still confused as to where I should insert the data.frame(x="") codes. I need to add the headers subjid.x to AEDIS as per my screenshot above and rtf_colheader as per my codes below. I need merged cell of "No data available in table" below my colheaders.

``` r
# Subset relevant cols for final listing generation
AESI <- subset(AE_CA_AESI, aeyn_si.factor=="Yes", select=c(subjid.x, dosegrp.factor, redcap_repeat_instance.x, AETERM_SOC_PT, AEST_EN_DAT_TIM, aeser.factor, AETOXGR_ACN_OUT, AEREL_CA_DRUG, AEDUR, AEDIS))

# Define table format
listing18_rtf <- AESI %>%
  rtf_page(
    orientation = "landscape",
    nrow = 2
  ) %>%
  rtf_page_header(
    text = c(paste0(PageHeader1), paste0(PageHeader2), paste0(PageHeader3)),
    text_justification = c("r", "l", "l"),
    text_font = 9,   # Courier New
    text_font_size = 8
  ) %>%
  rtf_page_footer(
    text = c("Notes:    Adverse events were coded using the Medical Dictionary for Regulatory Activities (MedDRA) Version 26.0.",
             "(d) = Day from challenge agent administration where day of administration = 0.",
             "AESI = Adverse Event of Special Interest; SAE = Serious adverse event; UN = Unknown; Dis. = Discontinuation",
             "",
             paste0("Printed: ", CurrentDate, " (", TFLVersion, ")")),
    text_font = 9,   # Courier New
    text_justification = "l",
    text_font_size = 8
  ) %>%
  rtf_title("Listing 18", "Adverse Events of Special Interest",
            text_font = 9,   # Courier New
            text_font_size = 8
  ) %>%
  rtf_colheader("Subject Number | Treatment Group | AE No | Adverse Event Verbatim/\n System Organ Class/\n Preferred Term | Onset Date and Time (d)/\n End Date and Time (d) | SAE | Severity (Grade)/\n Action Taken/\n Outcome | Related to Challenge Agent/\n Antimalarial Medication | Duration (hours) | Dis.",
                col_rel_width = c(0.9, 1.1, 0.5, 1.8, 1.4, 0.5, 1.8, 2, 1, 0.6),
                text_font = 9,   # Courier New
                text_justification = "c",
                text_font_size = 8,
                text_format = "b"
  ) %>%
  rtf_body(
    text_font = 9,   # Courier New
    text_justification = "c",
    text_font_size = 8,
    border_top = "single"
  )

# Output .rtf file
listing18_rtf %>%
  rtf_encode() %>%                                                   
  write_rtf(file = "18_Listings_Adverse_Events_of_Special_Interest.rtf") 
```

<sup>Created on 2023-03-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by BrianLang** [comment]
> Hi again,
> 
> I am still confused as to where I should insert the data.frame(x="") codes. I need to add the headers subjid.x to AEDIS as per my screenshot above and rtf_colheader as per my codes below. I need merged cell of "No data available in table" below my colheaders.
> 
> ```r
> # Subset relevant cols for final listing generation
> AESI <- subset(AE_CA_AESI, aeyn_si.factor=="Yes", select=c(subjid.x, dosegrp.factor, redcap_repeat_instance.x, AETERM_SOC_PT, AEST_EN_DAT_TIM, aeser.factor, AETOXGR_ACN_OUT, AEREL_CA_DRUG, AEDUR, AEDIS))
> ``` 

### This is where you'd check to see if your data.frame is empty.
You might also need to adjust `col_rel_width` for the fact that you only have one cell.
```r

if(nrow(AESI) == 0){
    AESI <- data.frame(x = "No data available in table")
}
```

> ``` r
> # Define table format
> listing18_rtf <- AESI %>%
>   rtf_page(
>     orientation = "landscape",
>     nrow = 2
>   ) %>%
>   rtf_page_header(
>     text = c(paste0(PageHeader1), paste0(PageHeader2), paste0(PageHeader3)),
>     text_justification = c("r", "l", "l"),
>     text_font = 9,   # Courier New
>     text_font_size = 8
>   ) %>%
>   rtf_page_footer(
>     text = c("Notes:    Adverse events were coded using the Medical Dictionary for Regulatory Activities (MedDRA) Version 26.0.",
>              "(d) = Day from challenge agent administration where day of administration = 0.",
>              "AESI = Adverse Event of Special Interest; SAE = Serious adverse event; UN = Unknown; Dis. = Discontinuation",
>              "",
>              paste0("Printed: ", CurrentDate, " (", TFLVersion, ")")),
>     text_font = 9,   # Courier New
>     text_justification = "l",
>     text_font_size = 8
>   ) %>%
>   rtf_title("Listing 18", "Adverse Events of Special Interest",
>             text_font = 9,   # Courier New
>             text_font_size = 8
>   ) %>%
>   rtf_colheader("Subject Number | Treatment Group | AE No | Adverse Event Verbatim/\n System Organ Class/\n Preferred Term | Onset Date and Time (d)/\n End Date and Time (d) | SAE | Severity (Grade)/\n Action Taken/\n Outcome | Related to Challenge Agent/\n Antimalarial Medication | Duration (hours) | Dis.",
>                 col_rel_width = c(0.9, 1.1, 0.5, 1.8, 1.4, 0.5, 1.8, 2, 1, 0.6),
>                 text_font = 9,   # Courier New
>                 text_justification = "c",
>                 text_font_size = 8,
>                 text_format = "b"
>   ) %>%
>   rtf_body(
>     text_font = 9,   # Courier New
>     text_justification = "c",
>     text_font_size = 8,
>     border_top = "single"
>   )
> 
> # Output .rtf file
> listing18_rtf %>%
>   rtf_encode() %>%                                                   
>   write_rtf(file = "18_Listings_Adverse_Events_of_Special_Interest.rtf") 
> ```
> 
> Created on 2023-03-31 with [reprex v2.0.2](https://reprex.tidyverse.org)

**Comment by riawoo** [comment]
This worked, I really appreciate this!!
