### ISSUE TITLE
Review r2rtf design pattern

### ISSUE THREAD

**Issue by elong0527** [Merck/r2rtf#16]
Hi Robert:

That would be great if you could review the r2rtf design pattern and provide suggestions if any. 

This is a document to help developer understand the logic behind `r2rtf`. We would like to improve this document for future collaborators. 

https://merck.github.io/r2rtf/articles/design-pattern.html 

@Robert-Krajcik

**Comment by Robert-Krajcik** [comment]
Sure I will take a look at this and get back to you in a couple of days.

**Comment by Robert-Krajcik** [comment]
I have reviewed this piece and opened it in MS Word and made changes to my copy of the document (not the examples).
I focused on grammar and punctuation, such as use of the definite article and the Oxford comma.
How do you want me to send you these changes?

**Comment by elong0527** [comment]
Thanks Robert! You may just attach it in the comment. (drag to the comment area) or you may send it to my email elong0527@gmail.com

**Comment by Robert-Krajcik** [comment]
I actually made a PR for you.
Update design-pattern.Rmd #17
You may have to assign yourself as a reviewer, @elong0527

**Comment by elong0527** [comment]
Design pattern updated 

https://merck.github.io/r2rtf/articles/design-pattern.html
