### ISSUE TITLE
RTF output turn to next page automatically when there are so many columns

### ISSUE THREAD

**Issue by wangben718** [Merck/r2rtf#164]
Do we consider add features to make RTF output turn to next page automatically when there are so many columns? Here is an output now if we have many columns.

![image](https://user-images.githubusercontent.com/85646030/236887616-03344372-cd5f-46eb-aabe-45b5471bd4a9.png)

**Comment by fb-elong** [comment]
No, that should be handled outside of r2rtf as there are many possible way split the page and arrange columns.
