### ISSUE TITLE
How to add cover and table of contents to combined rtf file

### ISSUE THREAD

**Issue by perphy** [Merck/r2rtf#173]
as the title described, we can only use assemble_rtf function to combine multiple rtf files into one , but can't add the table of content and cover for it? how do you deal with this problem?

**Comment by elong0527** [comment]
It is out of scope for r2rtf.

In Microsoft Word, You can get a TOC manually by

1. Select text in similar format (assuming titles have format different from table bodys)

https://www.laptopmag.com/articles/select-text-similar-formatting-word

2. Define them as a named format.

3. Use the format to define your TOC in word.

https://support.microsoft.com/en-us/office/format-or-customize-a-table-of-contents-9d85eb9c-0b55-4795-8abb-a49885b3a58d

You may try to handle it programmatically as you can either pre-specify title or extract title from RTF. 

Here is a toy example : https://merck.github.io/metalite/articles/ar-grid.html
