### ISSUE TITLE
Download for pageby-disposition.pdf is broken in RTF Examples for Tables with Pageby Feature Vignette

### ISSUE THREAD

**Issue by mstackhouse** [Merck/r2rtf#18]
The download tells me "No File" when trying to retrieve the PDF.

**Comment by elong0527** [comment]
Yes! we are enhancing the documentation. You may refer all outputs in 

https://github.com/Merck/r2rtf/tree/master/vignettes/rtf

**Comment by elong0527** [comment]
PDF preview have all been fixed to prepare v0.3.0 release.
