### ISSUE TITLE
Pkgdown fails on Master

### ISSUE THREAD

**Issue by BrianLang** [Merck/r2rtf#185]
**Describe the bug**
Currently the pkgdown action fails on master (pkgdown run #272). It throws an error that `tidyr` does not exist. `tidyr`, while being loaded by `library(tidyr)` in the vignettes, is not in the DESCRIPTION suggests field.

**Expected behavior**
pkgdown build actions should not fail on master.

**To reproduce**
Go to the GitHub actions and re-run the pkgdown build on master. 

**Session info**
CICD

**Additional context**
Found this out because #184 failed pkgdown build for the same reason, though the code does not touch anything related to vignettes.

**Comment by elong0527** [comment]
closed by #184
