### ISSUE TITLE
rtf_paragraph not getting loaded

### ISSUE THREAD

**Issue by sanjayssane** [Merck/r2rtf#19]
I have written the following code:

`res <- rtf_paragraph(rtf_text(quest_text),justification = "l")`
`write_rtf_para(res, "questions.rtf")`

I am getting error message as could not find function "write_rtf_para". I found that the rtf_paragraph and also rtf_text also are not getting loaded.

**Comment by elong0527** [comment]
`write_rtf_para` is an internal function. You will need to use `r2rtf:::write_rtf_para`. 

Reference: https://stackoverflow.com/questions/2675502/what-does-the-symbol-mean-in-r

**Comment by sanjayssane** [comment]
Thanks @elong0527 !
