### ISSUE TITLE
styler CI/CD fail

### ISSUE THREAD

**Issue by elong0527** [Merck/r2rtf#190]
The styler CI/CD fail without actionable information. 

https://github.com/Merck/r2rtf/actions/runs/5496535095/jobs/10016656138

Output: 

```
HEAD detached at v1.1.0
nothing to commit, working tree clean
No changes to commit
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>
```

**Comment by nanxstats** [comment]
Oh, this is a workflow issue where it fails the running for new GitHub releases. You can report it to r-lib/actions.

In any case, I created a PR to update the workflow since there seems to be some updates from upstream: https://github.com/Merck/r2rtf/pull/191
