### ISSUE TITLE
border_first & page_by

### ISSUE THREAD

**Issue by Amex-AZ** [Merck/r2rtf#195]
How to use the border_first parameter or another methods to display a line below the title on each page. 

**Context**
part of my current code:
rtf_page(orientation = "portrait", **border_first ="single",** border_last = "single") %>%
 rtf_title(title = "Table 14.X.X", subtitle = c("Full Analysis Set"), text_justification = "c", text_font_size = 9) %>%
    rtf_body(as_colheader = FALSE,
             col_rel_width = c(8, 5, 5, 5, 5, 5, 5),
             border_first = rep("single", 7),
             border_last = rep("single", 7),
             border_left = rep("", 7),
             border_right = rep("", 7),
             text_justification = c("l", "l", "c", "c", "c", "c", "c"),
             text_font_size = 7,
             **page_by = "groupn",**
             new_page = TRUE,
             last_row = FALSE) %>%
   rtf_encode( 
                doc_type = "table",
                page_title = "all",
                page_source = "last",
                verbose = FALSE) %>%
  write_rtf(rtf_filename)

I have three rtf pages that have been output grouped by (page_by = "groupn"). However, the border_first ="single" only appears after the title on page one. I want a single line following the title on each of the three pages.

**Comment by elong0527** [comment]
Please provide a screenshot of the current output and another screenshot of expected output.

Please also provide a reproducible code example using a dummy dataset.

**Comment by Amex-AZ** [comment]
Based on the dummy code below, this is the current output (yellow highlight for missing line below page title 2).:
![image](https://github.com/Merck/r2rtf/assets/131464680/4bc61db4-02d4-4702-b1c1-1bb58f652240)

expected output: 
![image](https://github.com/Merck/r2rtf/assets/131464680/7c84ad27-4786-4149-a622-5e3c3de9d3ca)

Reproducible code example
`
library(r2rtf)
library(dplyr)
library(tidyr)
# Generate dummy data for testing
set.seed(123) # Setting seed for reproducibility
n <- 100
adsl3 <- data.frame(
  AGE = sample(18:80, n, replace = TRUE),
  SEX = sample(c("M", "F"), n, replace = TRUE),
  RACE = sample(c("ASIAN", "WHITE", "BLACK", "HISPANIC"), n, replace = TRUE),
  TRT01A = sample(c("Drug1", "Drug2", "Placebo"), n, replace = TRUE),
  HEIGHTBL = rnorm(n, mean = 170, sd = 10),
  WEIGHTBL = rnorm(n, mean = 70, sd = 12),
  BMIBL = rnorm(n, mean = 25, sd = 5)
)

# Create the dummy function BaselineTables 
BaselineTables <- function(adsl3, condition_inputs) {
  tables <- list()
  
  for (i in 1:length(condition_inputs)) {
    condition <- condition_inputs[[i]]
    table_name <- paste0("Baseline_Table_", i)
    
    table <- adsl3 %>%
      filter(!!!condition)
    
    # Calculate summary statistics
    result <- table %>%
      group_by(TRT01A) %>%
      summarise(across(c(HEIGHTBL, WEIGHTBL, BMIBL), list(
        N = ~ sum(!is.na(.)),
        Mean = ~ round(mean(., na.rm = TRUE), 1),
        SD = ~ round(sd(., na.rm = TRUE), 1),
        Median = ~ round(median(., na.rm = TRUE), 1),
        Min = ~ round(min(., na.rm = TRUE), 1),
        Max = ~ round(max(., na.rm = TRUE), 1)
      ), .names = "{.col}_{.fn}")) %>%
      ungroup()
    
    # Add total row for summary statistics
    total_row <- table %>%
      summarise(across(c(HEIGHTBL, WEIGHTBL, BMIBL), list(
        N = ~ sum(!is.na(.)),
        Mean = ~ round(mean(., na.rm = TRUE), 1),
        SD = ~ round(sd(., na.rm = TRUE), 1),
        Median = ~ round(median(., na.rm = TRUE), 1),
        Min = ~ round(min(., na.rm = TRUE), 1),
        Max = ~ round(max(., na.rm = TRUE), 1)
      ), .names = "{.col}_{.fn}")) %>%
      mutate(TRT01A = "Total") %>%
      ungroup()
    
    # Combine result and total row
    result <- bind_rows(result, total_row)
    
    # Add summary statistics to the table
    table_summary <- list(data = table, summary = t(result))
    tables[[table_name]] <- table_summary
  }
  
  return(tables)
}

# Specify the data and conditions.
con_data <- adsl3
condition_inputs <- list(
  condition1 = list(adsl3$AGE >= 18, adsl3$SEX == "M"),
  condition2 = list(adsl3$RACE %in% c("ASIAN", "WHITE")),
  condition3 = list(adsl3$AGE >= 18, adsl3$SEX == "F")
)

# Call BaselineTables function
baseline_tables <- BaselineTables(con_data, condition_inputs)


#test output 
bc_condition1 <-baseline_tables$Baseline_Table_1$summary

convert_summary_table <- function(bc_conditions) {
  # Create an empty data frame to store the final result
  bc_final <- data.frame()
  
  # Loop through each bc_condition in bc_conditions
  for (bc_condition in bc_conditions) {
    # Convert summary_table to a data frame for the current bc_condition
    summary_table <- as.data.frame(bc_condition)
    colnames(summary_table) <- c("Drug1", "Drug2", "Placebo", "Total")
    
    # Remove the first row
    summary_table <- summary_table[-1, ]
    
    # Create a sample data frame
    df <- data.frame(A = 1:18, B = letters[1:18])
    
    # Add a new column with values
    sat_column <- c("N", "Mean", "SD", "Median", "Min", "Max", "N", "Mean", "SD", "Median", "Min", "Max", "N", "Mean", "SD", "Median", "Min", "Max")
    
    Lab_col <- c("Height (cm)", "", "", "", "", "", "Weight (kg)", "", "", "", "", "", "BMI (kg/m2)", "", "", "", "", "")
    
    
    final <- cbind("Label" = Lab_col, "Statistics" = sat_column, summary_table)
    
    
    # Value to search for
    given_value <- "N"
    
    # Find the rows with the given value
    index <- which(final$Statistics == given_value)
    
    # Create an empty row
    empty_row <- rep("", ncol(final))
    
    # Add a blank line before each occurrence of the given value
    for (i in rev(index)) {
      final <- rbind(final[0:(i - 1), ], empty_row, final[i:nrow(final), ])
    }
    
    # Append the final result for the current bc_condition to bc_final
    bc_final <- rbind(bc_final, final)
  }
  
  return(bc_final)
}

bc_conditions <- list(baseline_tables$Baseline_Table_1$summary,
                      baseline_tables$Baseline_Table_2$summary,
                      baseline_tables$Baseline_Table_3$summary)

bc_final <- convert_summary_table(bc_conditions)

# add three groupn for each pages
for (i in seq_len(nrow(bc_final))) {
  if (i <= 22) {
    bc_final$groupn[i] <- 1
  } else if (i <= 43) {
    bc_final$groupn[i] <- 2
  } else if (i <= 64) {
    bc_final$groupn[i] <- 3
  }
}

#rtf code
bc_final %>%
    rtf_page(orientation = "portrait", border_first ="single", border_last = "single") %>%
    rtf_title(title = "Table 14.x.x", subtitle = c("BC", "Full Analysis Set"), text_justification = "c", text_font_size = 9) %>%
    rtf_colheader(colheader = " |Statistics | Drug1 | Drug2  | Placebo  | Total | " ,
                  col_rel_width = c(6, 4, 3, 3, 3, 3),
                  text_justification = c("c", "c", "c", "c", "c", "c"),
                  border_top = rep("", 6),
                  border_right = rep("", 6),
                  border_left = rep("", 6)) %>%
    rtf_body(as_colheader = TRUE,
             col_rel_width = c(6, 3, 3, 3, 3, 3),
             border_first = rep("single", 6),
             border_last = rep("single", 6),
             border_left = rep("", 6),
             border_right = rep("", 6),
             text_justification = c("c", "c", "c", "c", "c", "c"),
             text_font_size = 6,
             page_by = "groupn",
             new_page = TRUE,
             last_row = FALSE) %>%
    rtf_encode() %>%
    write_rtf("dummy_bc.rtf")
`

**Comment by elong0527** [comment]
To achieve your goal, you should use ` border_top = rep("single", 6)` in `rtf_colheader` instead of ` border_top = rep("", 6)`

The `border_first` and `border_last` in `rtf_page` is to control the first and last line of the whole table.

**Comment by Amex-AZ** [comment]
Thanks, It worked!
