### ISSUE TITLE
Variations in RTF output across package versions

### ISSUE THREAD

**Issue by nanxstats** [Merck/r2rtf#196]
It seems that the same R code can produce varying RTF outputs across r2rtf versions (on the source level), likely due to the introduction of new RTF commands. On the upside, these outputs remain consistent across different platforms.

However, this variation can potentially complicate snapshot testing. When saving RTF files as snapshots, if the development and production environments are using different versions of r2rtf, it could cause check errors in the CI/CD builds.

I'm trying to limit the scope of this issue. As a starter, I wonder if we should improve our documentation to capture these changes, perhaps with the help of a vignette. Would appreciate your thoughts on this.

**Comment by elong0527** [comment]
Yes, it is definitely possible to have different RTF snapshot source code from different r2rtf version.

I think the general practice is to ensure your test pass current version of an R package. The snapshot should be updated after proper checking the results.
