### ISSUE TITLE
Underscore rendering

### ISSUE THREAD

**Issue by nielsonc** [Merck/r2rtf#2]
An option is needed to allow r2rtf to print underscores (eg, in path names) rather than converting subsequent text to subscript.

**Comment by elong0527** [comment]
`text_convert` argument is introduced in `rtf_*`. Set it to `FALSE` will not convert underscores to subscript.

**Comment by GlicketySplit** [comment]
Hey @elong0527 

If one wanted to include multiple lines of text that include some underscores using rtf_page_footer(), how would one do so?

When text_convert = TRUE, "\n" does not appear to allow a line break. 
And separating the text into multiple rtf_page_footer() calls does not work either. 

Example: 

`myRTF %>% rtf_page_footer(text = "First line\nmy_file_path\nThird line", text_convert = TRUE)`

**Comment by elong0527** [comment]
If my understanding is correct, you mean `text_convert = FALSE`. In such case `\n` will not be converted to RTF syntax. 

You will need some background on RTF syntax in such case, for example, new line is `\line` in RTF. In your example, it will be 

reference: https://www.oreilly.com/library/view/rtf-pocket-guide/9781449302047/ch01.html

```
library(r2rtf)
iris %>% 
  rtf_body() %>% 
  rtf_page_footer(text = "First line\\line my_file_path\\line Third line", text_convert = FALSE) %>% 
  rtf_encode() %>% 
  write_rtf("tmp.rtf")
```

**Comment by GlicketySplit** [comment]
Ah, yes I meant `text_convert = FALSE`.

This is great. Thank you for the link & example code!
