### ISSUE TITLE
Create FAQ vignette

### ISSUE THREAD

**Issue by nanxstats** [Merck/r2rtf#205]
**Is your feature request related to a problem? Please describe.**
I want a single source to see standard answers for frequently asked questions from users.

**Describe the solution you'd like**
Create a vignette that collects common questions and answers, possibly starting from existing resolved GitHub issues.

**Describe alternatives you've considered**
Searching on Google or GitHub issues would be possible alternatives but doesn't create much value if your keywords are wrong.

**Additional context**
I created a [FAQ vignette for ggsci](https://nanx.me/ggsci/articles/ggsci-faq.html) before and found it useful.

**Comment by elong0527** [comment]
Maybe we can consider it in the future?

After checking all 12 issues tagged as "question". They are all unique questions.

**Comment by nanxstats** [comment]
Of course. I surely appreciate the breadth of the current questions and hopefully there will be more repeating topics to be summarized in the future.
