### ISSUE TITLE
Release r2rtf 1.1.1

### ISSUE THREAD

**Issue by wangben718** [Merck/r2rtf#208]
Prepare for release

- [x] Check current CRAN check results
- [x] Check licensing of included files
- [x] Review pkgdown reference index for, e.g., missing topics
- [x] Bump version
- [ ] Update `cran-comments.md` (optional)
- [x] Update NEWS.md
- [x] Review pkgdown website
- [x] `urlchecker::url_check()`
- [ ] Check with local machine
- [ ] Check with GitHub Actions
- [ ] Check with win-builder

Submit to CRAN

- [ ] Draft GitHub release
- [ ] Submit to CRAN via web form
- [ ] Approve emails

Wait for CRAN

- [ ] Accepted :tada:
- [ ] Post on r-packages mailing list
- [ ] Tweet

**Comment by nanxstats** [comment]
@wangben718 I see this has been released on CRAN - please draft a GitHub release following the checklist.
