### ISSUE TITLE
Page number

### ISSUE THREAD

**Issue by nielsonc** [Merck/r2rtf#3]
An option to include pagination below each table (eg, "Page 1 of 2") is needed.

**Comment by elong0527** [comment]
It is addressed in development version v0.1.1.9001.

Please refer `rtf_page_header` and `rtf_page_footer`. 

The defalut value of `rtf_header` allow RTF to have a dynamic field. `"Page \\chpgn  of {\\field{\\*\\fldinst NUMPAGES }}"`
