### ISSUE TITLE
Add missing fields to the vignettes yaml header

### ISSUE THREAD

**Issue by nanxstats** [Merck/r2rtf#30]
Right now, no vignettes shows up on [CRAN](https://cran.r-project.org/package=r2rtf).

This is probably due to the missing [settings](https://bookdown.org/yihui/rmarkdown/r-package-vignette.html) in the vignette yaml header, such as `%\VignetteEngine{}` and `%\VignetteIndexEntry{}`. Consider adding them.

```yaml
---
title: "What the Vignette Does"
...
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{What the Vignette Does}
---
```

**Comment by elong0527** [comment]
For r2rtf, I did not plan to submit Vignette to CRAN, because I will also have RTF, PDF, html, and docx file associated with the output. So I ignore all of them while building the package.

https://github.com/Merck/r2rtf/blob/0fa98a9199d550749911f3fbefb2c45f0ede7712/.Rbuildignore#L7

**Comment by nanxstats** [comment]
I see, that makes sense.

In this case, can you create a placeholder vignette, to point people to the pkgdown website page, like [what DT did](https://github.com/rstudio/DT/tree/master/vignettes)? This way, there is at least a page on CRAN pointing people to the actual vignettes.

**Comment by elong0527** [comment]
added one and updated `.Rbuildignore`

https://merck.github.io/r2rtf/articles/r2rtf-cran.html

**Comment by elong0527** [comment]
Received an unexpected error 

https://github.com/Merck/r2rtf/runs/2699045324?check_suite_focus=true

**Comment by elong0527** [comment]
addressed in https://github.com/Merck/r2rtf/commit/965a42c03c1dca7d6da8250fd68af4bd3b586f49

**Comment by nanxstats** [comment]
Great! I'm closing this.
