### ISSUE TITLE
Double top and bottom borders

### ISSUE THREAD

**Issue by sanjayssane** [Merck/r2rtf#31]
Whenever I have kept no borders for left and right, I have seen that the double borders get applied to top and bottom of the report. Please see the rtf file in the zip file.

I am attaching my all data file, R program file and rtf files.
[tbl_14_1_4.zip](https://github.com/Merck/r2rtf/files/6600315/tbl_14_1_4.zip)

Can these double borders of top and bottom be made as single borders? I saw all the vignette examples and did not get any solution to my problem.

**Comment by elong0527** [comment]
The top and bottom border is controlled by `rtf_page`

It can be controlled by the two arguments below. 

```
  border_first = "double",
  border_last = "double",
```

Example can be found in #12

**Comment by sanjayssane** [comment]
Thanks a lot @elong0527 
I did 
border_first = "single",
border_last = "single" 
and it got solved.
