### ISSUE TITLE
Different titles for multiple figures

### ISSUE THREAD

**Issue by sanjayssane** [Merck/r2rtf#32]
I have 6 figures in all (each parameter for Vital Signs, say). The one combined rtf for all 6 figures was generated with usual rtf options indicated in /vignettes/example-figure.Rmd. But I want to put different titles to different figures on each page. 
By which option can I do this?

**Comment by elong0527** [comment]
The r2rtf is design to have table/figure with common style per file. 

If you need to combine multiple different figures, the workflow could be

1. create one figure per rtf file 
2. combing multiple RTF files into one (r2rtf did not officially support this step). 

You can see a working example as below.

```
library(r2rtf)
library(magrittr)

png("fig1.png")
  plot(1:10)
dev.off()  

png("fig2.png")
  plot(1:10)
dev.off()  

file1 <- "fig1.png"

file2 <- "fig2.png"

file1_rtf <- file1 %>%
  rtf_read_png() %>%                     # read PNG files from the file path
  rtf_title("title", "subtitle") %>%     # add title or subtitle
  rtf_encode(doc_type = "figure")     # encode rtf as figure


file2_rtf <- file2 %>%
  rtf_read_png() %>%                     # read PNG files from the file path
  rtf_title("another title", "another subtitle") %>%     # add title or subtitle
  rtf_encode(doc_type = "figure")    # encode rtf as figure

# Combine other figure RTF body to the first one  
file1_rtf$body <- paste(file1_rtf$body, file2_rtf$body, sep = r2rtf:::as_rtf_new_page() )  

file1_rtf %>% write_rtf("output.rtf")
```

**Comment by sanjayssane** [comment]
Got it. Thanks a ton @elong0527 !
