### ISSUE TITLE
Splitting table into parts when there are more columns than can fit on one page

### ISSUE THREAD

**Issue by PSSathe** [Merck/r2rtf#34]
Hi, 
I want to generate a table where there are too many columns (>20). To fit all the columns in one page (landscape format), I can reduce the font size, but then it becomes unreadable.
Is there a way to split the table after certain number of columns and get part 1 of page X, part 2 of page X
Thanks

**Comment by elong0527** [comment]
`r2rtf` did not directly support this feature, you may just need to implement this in your own wrap up function. 

1. split the data multiple smaller data
2. create table for each data
3. combine them into one RTF file

you can refer #32 to combine multiple RTF file into one.

**Comment by PSSathe** [comment]
Thanks

- Prachi Sathe
