### ISSUE TITLE
Margins options

### ISSUE THREAD

**Issue by nielsonc** [Merck/r2rtf#4]
The ability to specify page margins or an option to choose the following set of margins is needed.

8.5 x 11 (US letter) paper
  | Portrait | Landscape
Top | 1.0" | 1.5"
Bottom | 0.75" | 1.0"
Left | 1.5" | 0.75"
Right | 1.0" | 1.0"

**Comment by elong0527** [comment]
It is addressed in development version v0.1.1.9001.

Please refer `rtf_page`
