### ISSUE TITLE
`text_format` issue with all value equal to `""`

### ISSUE THREAD

**Issue by elong0527** [Merck/r2rtf#40]
An error below shall be avoid. 

```
library(r2rtf)

f <- rep("", ncol(iris))

iris %>% 
  rtf_body(text_format = f)
```

hot fix: 

```
library(r2rtf)

f <- rep("", ncol(iris))

if(all(f == "")) f <- NULL

iris %>% 
  rtf_body(text_format = f)
```

**Comment by elong0527** [comment]
The same issue may happen in `border_type`,  we probably need to update `check_args` to allow it recognize `""` as input.

**Comment by yesimiao** [comment]
@elong0527  fixed under https://github.com/Merck/r2rtf/pull/41, pending review
