### ISSUE TITLE
The Font size doesn't consistency between function default value and the Arguments description

### ISSUE THREAD

**Issue by DawnYe** [Merck/r2rtf#44]
Take an example: [rtf_page_header](https://merck.github.io/r2rtf/reference/rtf_page_header.html)

```
rtf_page_header(
  tbl,
  text = "Page \\pagenumber of \\pagefield",
  text_font = 1,
  text_format = NULL,
  text_font_size = 12,
  text_color = NULL,
  text_background_color = NULL,
  text_justification = "r",
  text_indent_first = 0,
  text_indent_left = 0,
  text_indent_right = 0,
  text_space = 1,
  text_space_before = 15,
  text_space_after = 15,
  text_convert = TRUE
)
```

The text font size in function default value is 12, while in Arguments description is 9. This in-consistence occurred in other functions, too.

<html>
<body>

text_font_size | Text font size. Default is 9. To vary text font size by column, use numeric vector with length of vector equal to number of columns displayed e.g. c(9,20,40).
-- | --

</body>
</html>

**Comment by elong0527** [comment]
Thanks! We will update the document.
