### ISSUE TITLE
Vertical Align Column Headers

### ISSUE THREAD

**Issue by kmkramer23** [Merck/r2rtf#49]
Is there a way to vertically align column headers in a table?  The headers default to top aligned and I would like to bottom align them.

**Comment by elong0527** [comment]
Could you provide a screenshot of what you are trying to achieve?

**Comment by kmkramer23** [comment]
I am trying to bottom align the headers so Subject and Best Response align with (Days) and Cohort along the bottom border header line.  By default I get table A but I want to VAlign:bottom to get table b.

Table A:
[cid:704f5dd8-5d3c-4946-a0c6-aa81f5ae8650]

Table B:
[cid:6f78e58a-dece-4581-81a2-4fa55f2f3bc2]

________________________________

**Comment by elong0527** [comment]
emm, seems the screenshot is not proper attached.

**Comment by kmkramer23** [comment]
I pasted the image into the email.  Let me know if you still cant see it.

I am trying to bottom align the headers so Subject and Best Response align with (Days) and Cohort along the bottom border header line.  By default I get table A but I want to VAlign:bottom to get table b.

Table A:
***@***.***

Table B:
***@***.***

**Comment by elong0527** [comment]
Nope~ you probably need to attach the image from github directly. 

Email to github seems not recognize attachment.

**Comment by kmkramer23** [comment]
See attached…

**Comment by elong0527** [comment]
Could you navigate to `https://github.com/Merck/r2rtf/issues/49` and attach images? 

I still can not see images when you reply by email.

**Comment by kmkramer23** [comment]
![image1](https://user-images.githubusercontent.com/89997171/131937155-4bcceb79-c596-45e6-9fd2-c20a0f4d1a0c.png)
![image2](https://user-images.githubusercontent.com/89997171/131937166-ce6d7c73-3196-4389-9bf0-a43c0993577e.png)

**Comment by elong0527** [comment]
Please find two examples below

If you know where you want to break the line, it is easier to control using `\\line`. 

```
library(r2rtf)

iris[1:3, 1:2] %>% 
  rtf_page(width = 4) %>%
  rtf_colheader(" Treatment \\line Cohort | \\line Subject") %>% 
  rtf_body() %>% 
  rtf_encode() %>% 
  write_rtf("tmp.rtf")
```

I have not enable vertical alignment in `r2rtf` but you can hack it by adding the `\\clvertalb` before each cell in column header. 

reference: http://www.biblioscape.com/rtf15_spec.htm

```
x <- iris[1:3, 1:2] %>% 
  rtf_page(width = 4) %>%
  rtf_colheader(" Treatment \\line Cohort | \\line Subject") %>% 
  rtf_body() %>%
  r2rtf:::rtf_encode_table(verbose = TRUE)
x$colheader <- gsub("\\cellx", "\\clvertalb\\cellx", x$colheader, fixed = TRUE)

x %>% write_rtf("tmp1.rtf")
```

**Comment by elong0527** [comment]
In PR #52, a new argument, `cell_vertical_alignment` has been added in `rtf_colheader` with default be `bottom` 

The output shall work directly. 

```
iris[1:3, 1:2] %>% 
    rtf_page(width = 4) %>%
    rtf_colheader(" Treatment Cohort |  Subject") %>% 
    rtf_body() %>%
    rtf_encode() %>% 
    write_rtf("tmp.rtf")
```
