### ISSUE TITLE
Enhancement idea for "Page X of Y" in RTF body

### ISSUE THREAD

**Issue by Robert-Krajcik** [Merck/r2rtf#6]
Hi Yilong,
and thanks for your email reply last Friday.

For companies where the RTF header and footer are reserved for regulatory publishing,
I came with this workaround, and wanted to share that with you and get your thoughts.  
This is similar to papers on SAS programming using ODS RTF that I would see on [pharmaSUG](www.pharmaSUG.org) 

Let’s say we create an RTF document using the `r2rtf::rtf_encode()` function.

`rtf_doc <- rtf_encode(ae_tbl)`

and it happened to have two title lines:
`rtf_title("Listing of Subjects With Serious Adverse Events", "#PageXofY")`

Here is an R function that uses Base R functions `gregexpr()` and `gsub()` instead of 'stringr::str_locate_all()` and `stringr::str_replace_all()` so as to minimize the package footprint.

`gregexpr()` returns a list of all the start positions of the control word “\page”
NumPages is simply the length of the list of the start positions, plus 1 (if there are no page breaks, then there is one page).
The replacement string, repl, uses the “\chpgn” control word and the NumPages coerced into a character.
the body of the RTF document is updated.  Every instance of “string” (the sentinel "#PageXofY") is replaced with “repl” using `gsub()`.

Encapsulating `\\chpgn` in the function means programmers don’t have to get their hands dirty with RTF command line coding.

```{r, eval=FALSE}
pagexofy <- function(rtf_doc, string = "#PageXofY") {
  # function to replace "string" with "Page X of Y" in RTF document body
  pages <- gregexpr("\\\\page", rtf_doc$body)  # \page = Required page break
  NumPages <- length(pages[[1]]) + 1
  repl <- paste("Page \\\\chpgn"," of", as.character(NumPages))
  rtf_doc$body <- gsub(string, repl, rtf_doc$body)
  return(rtf_doc)
}
```

Next we update the document and write it out.
`pagexofy(rtf_doc) %>% 
  write_rtf("pageby-ae-listing.rtf")`

-or-

`rtf_encode(ae_tbl) %>% pagexofy() %>% write_rtf("paged-ae-table.rtf")`

**Comment by elong0527** [comment]
Thanks Richard for the suggestion. 

I have added three new keywords related to page number. This will allow user to display page number in any place. 

`\\pagenumber`
`\\totalpage`
`\\pagefield`

In your example, the code below shall provide the expected output. 

```
iris %>% rtf_title("Page \\pagenumber of \\totalpage", "Page \\pagenumber of \\pagefield") %>% 
               rtf_body() %>%
               rtf_encode() %>% 
               write_rtf("tmp.rtf")
```

`\\pagefield` is adding a toggle filed. One drawback is that the filed requires [manual refresh](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_winother-mso_2010/updating-all-fields-in-a-word-document/4462e35a-6284-4804-bd38-0514c852b616)

**Comment by Robert-Krajcik** [comment]
Thanks for this, Yilong

I will definitely try it out. 
Am I able to download this yet?

Robert

**Comment by elong0527** [comment]
Yes, I have updated the master branch.

**Comment by Robert-Krajcik** [comment]
Thanks so much, @elong0527 

Yes it works.  The `\\pagefield` appeared after I selected File -> Print
But ``\\pagenumber`  and `\\totalpage` will be sufficient for our needs.
Much simpler than writing a function.   
You can close this issue whenever you are ready.

Thanks again.
Robert

![image](https://user-images.githubusercontent.com/62262182/99703267-e7dc4200-2a64-11eb-936c-8d1492d7b7e0.png)
