### ISSUE TITLE
Improve program discovery in rtf_convert_format()

### ISSUE THREAD

**Issue by nanxstats** [Merck/r2rtf#64]
We can potentially improve `rtf_convert_format()` to:

1. Make it not libreoffice-version-dependent.
   This can be easily fixed by not calling `libreoffice7.1`. Although you can specify a minimum version, see next.
1. Make the program discovery robust to different systems types and libreoffice versions.
   `rmarkdown::find_pandoc()` is a good example I can think of, it uses `rmarkdown:::find_program()`.

1. Optimize the call parameters.
    Maybe look into [this](https://github.com/vladgolubev/docker-libreoffice-pdf-cli/blob/master/Dockerfile) and [this](https://help.libreoffice.org/3.3/Common/Starting_the_Software_With_Parameters).

This update will need testing on different infrastructures but I guess it's doable.

**Comment by elong0527** [comment]
RStudio bundle `pandoc` using `Sys.getenv("RSTUDIO_PANDOC")`. 

I had a challenge to identify latest version of `libreoffice` in Linux, because the system set it up in different command. 

```
$ libreoffice --version
LibreOffice 5.3.6.1

$ libreoffice7.1 --version
LibreOffice 7.1.2.2 
```

**Comment by elong0527** [comment]
The PR #68  allow libreoffice-version-dependent

- the change shall enable the code in Windows and MAC, but I am not sure if this can be tested in github action. So I still limited to Linux in the source code. 

- For item 3, would you suggest me to add the options below? 

```
--invisible --headless --nologo --convert-to
```

**Comment by nanxstats** [comment]
Good - let me look into this and get back to you a bit later.

**Comment by elong0527** [comment]
Would you feel we can close this issue?

**Comment by nanxstats** [comment]
I'm closing this as progress has been made. Good work! I created a new issue to document a possible "full fix": https://github.com/Merck/r2rtf/issues/92
