### ISSUE TITLE
Adding Vector Graphs

### ISSUE THREAD

**Issue by kmkramer23** [Merck/r2rtf#65]
Can you incorporate functionality to add vector graphs like EMF to the rtf file?  There is a package called devEMF which will create the EMF files just need the functionality to add it to the RTF file.

**Comment by kmkramer23** [comment]
Adding to the above, I was able to incorporate an EMF file into the RTF document by reading it in using the r2rtf function rtf_read_png() and after encoding it into RTF, changing the pngblip tag to emfblip using gsub.

**Comment by elong0527** [comment]
Could you share an example code for incorporate an EMF file? I will try to think how to extend `r2rtf` for EMF files.

**Comment by kmkramer23** [comment]
library(r2rtf)
library(ggplot2)
library(devEMF)

graph_file <- tempfile("figure_",fileext=".emf")

devEMF::emf(file = graph_file, width = 8, height = 5, family = "Helvetica", pointsize = 8,
            emfPlus = TRUE, emfPlusRaster = TRUE, emfPlusFont = TRUE, custom.lty = TRUE)

figure <- ggplot(mtcars, aes(x = wt, y = mpg)) +
          geom_point()

print(figure)

dev.off()

rtf <-  rtf_read_png(graph_file) %>%
    rtf_figure() %>%
    rtf_encode(doc_type = "figure")

rtf$body <- gsub("pngblip", "emfblip", rtf$body, fixed = TRUE)

write_rtf(rtf, file = "fig-emf.rtf")

**Comment by kmkramer23** [comment]
Now that its a vector image you can resize without distorting the image and edit it.  You can't however, edit the image when you open it with Word but you can use a graphics editor package like Adobe or Inkscape to edit it.

**Comment by JianminLong0** [comment]
Microsoft Word/RTF has a easy way to handle a few types pictures, and the 3 most useful ones are PNG, EMF and JPEG.  r2rtf knows how to include PNG files, and you can replace PNG with EMF or JEPG to do the same.  In RTF, you can easily do Picture Size, Scaling, and Cropping, and if want you can also rotate and flip the pictures in many ways.  So keep r2rtf independent of other R-packages in kmkramer23's example code.

**Comment by elong0527** [comment]
The PR #67 allow r2rtf to use `jpeg`, `emf` and `png` now. 

```
library(r2rtf)
library(devEMF)

# Create EMF file
emf("tmp.emf")

plot(1:10)

dev.off()

# Create jpeg file
jpeg("tmp.jpeg")

plot(11:20)

dev.off()

# Create png file 
png("tmp.png")

plot(21:30)

dev.off()

# Embed into RTF file
rtf_read_figure(c("tmp.emf", "tmp.jpeg", "tmp.png")) %>%
  rtf_figure() %>%
  rtf_encode(doc_type = "figure") %>% 
  write_rtf(file = "fig.rtf")
```

**Comment by elong0527** [comment]
PR #67 merged.
