### ISSUE TITLE
How to adjust cell height after convert to html

### ISSUE THREAD

**Issue by elong0527** [Merck/r2rtf#66]
The converted html file has a larger cell height than expected. 

https://htmlpreview.github.io/?https://github.com/Merck/r2rtf/blob/master/vignettes/html/ae_example.html

We need to find a way to adjust cell height. (maybe using CSS?)

**Comment by nanxstats** [comment]
If we have to consider broader compatibility and rely on libreoffice to do RTF -> HTML, then I guess post-processing the HTML and modify the CSS is a possibility (should be simple to try).

If our goal is creating an HTML that looks exactly like the PDF, then I guess a worthy option is [pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX), an almost magical tool that coverts PDF into HTML and keeps the exact appearance. So the path is RTF -> PDF -> HTML.

An important limitation of this is that the original pdf2htmlEX was deprecated by the author and is now maintained by other people as a forked repo above. It is not distributed from official package repos so probably not a good idea to implement in an R wrapper for regular users. It's totally ok though for package internal use in GitHub Actions if that's the scope.

**Comment by fb-elong** [comment]
It see a simple fix to remove `line-height: 115%;` in the html source code.
