### ISSUE TITLE
Broken link on the pkgdown site

### ISSUE THREAD

**Issue by nanxstats** [Merck/r2rtf#7]
Maybe this is a placeholder page but we should make the links work.

Steps to reproduce:

- Go to https://merck.github.io/r2rtf/
- Click Validation in the navigation bar
- Click Validation Plan and Track

Page shows a 404 and links on the page are not working (probably because pkgdown uses relative paths).

**Comment by elong0527** [comment]
Thanks Nan, I have removed the validation tab as it shall only for internal SDLC process.

**Comment by nanxstats** [comment]
Great! LGTM
