### ISSUE TITLE
update pkgdown template 

### ISSUE THREAD

**Issue by elong0527** [Merck/r2rtf#70]
pkgdown CSS template needs to be updated after using Bootstrap 5 with pkgdown 2.0.0 

https://merck.github.io/r2rtf/index.html

pkgdown release notes: https://www.tidyverse.org/blog/2021/12/pkgdown-2-0-0/

@nanxstats

**Comment by nanxstats** [comment]
Looks good. Will look into this. The customization looks much easier now and can potentially save a lot of CSS.

**Comment by nanxstats** [comment]
This is fixed by https://github.com/Merck/r2rtf/pull/73
