### ISSUE TITLE
Add parameter for left and right cell margins

### ISSUE THREAD

**Issue by tdwils** [Merck/r2rtf#79]
The RTF table output has cell margins left = 0.08” and right = 0.08”. Is there a way to change these values? We often have tables with many columns, and it would be nice to be able to adjust these margins. Would it be possible to add a parameter so we can change the right and left cell margins? I think it would need to be added to at least rtf_colheader() and rtf_body().

Below is a reproducible example and a screenshot from Word.

```
library(r2rtf)
library(dplyr)
library(tidyr)

tbl <- r2rtf_adae %>%
  count(TRTA, AEDECOD) %>%
  pivot_wider(names_from = TRTA, values_from = n, values_fill = 0)

head(tbl) %>%
  rtf_body() %>% 
  rtf_encode() %>% 
  write_rtf("rtf/intro-ae1.rtf") 
```

![image](https://user-images.githubusercontent.com/16843423/146411852-ece5888c-41d5-42c6-af88-6fc340420a13.png)

**Comment by elong0527** [comment]
Please check the "margin" argument in "rtf_page".

https://merck.github.io/r2rtf/reference/rtf_page.html

You also need the "col_width" to define the total column width if you need more space.

**Comment by tdwils** [comment]
I thought the “margin” argument in “rtf_page” controlled the page margins. We are looking for a way to control the margins of the table cells.

![image](https://user-images.githubusercontent.com/16843423/146426602-59fbaa44-2a98-4808-8098-e04d7a311ed4.png)

For example, below is an example with the right/left cell margins = 0.0” and 0.5”. (r2rtf seems to use 0.08” by default)

![image](https://user-images.githubusercontent.com/16843423/146426702-560b0c2b-0a3d-41f2-b646-d17a8113f1f0.png)

**Comment by Jianminlong** [comment]
Hi @tdwils and @elong0527 , the cell margin is controlled by the control word \trgaph, and here is the definition from RTF specs: 

\trgaphN    Half the space between the cells of a table row in twips.

So, 0.08 in in @tdwils 's case is a round number of 0.075 = 108/(72*20), also in the same example, the table row is controlled by

\trowd\trgaph108\...

So, you need an option to change the gap between cells of a table row.  Note that cell margin is half of the gap.

**Comment by elong0527** [comment]
wow, @Jianminlong you know a lot details in RTF specification. 

Yes, the value 108 is hard-coding and I did not expect user to modify them. 

@tdwils, thanks for the clarification. I misunderstood your original question. 

You can specify `text_indent_xxx` arguments with negative value to achieve the similar goal with example code below. 

More examples can be find in https://merck.github.io/r2rtf/articles/rtf-text.html#indent

```
library(r2rtf)
library(dplyr)
library(tidyr)

tbl <- r2rtf_adae %>%
  count(TRTA, AEDECOD) %>%
  pivot_wider(names_from = TRTA, values_from = n, values_fill = 0)

head(tbl) %>%
  rtf_page(col_width = 5) %>%
  rtf_colheader(colheader = paste(names(tbl), collapse = "|"), 
                text_indent_first = -108,
                text_indent_left = -108,
                text_indent_right = -108) %>%
  rtf_body(text_indent_first = -108, 
           text_indent_left = -108, 
           text_indent_right = -108) %>% 
  rtf_encode() %>% 
  write_rtf("intro-ae1.rtf") 
```

**Comment by tdwils** [comment]
Thank you for the example. This produces the effect we are looking for.

Our tables also have a subline, and the subline is being affected by the text_indent_xxx parameters. Is there a way we can control the alignment of the subline separately from the table cell contents? The subline needs to be left-aligned with the table. I found a workaround by adding non-breaking spaces to the beginning of the subline text, but I was just wondering if there is parameterized way to do this. Below is the code and the view of the RTF in Word.


```
library(r2rtf)
library(dplyr)
library(tidyr)

tbl <- r2rtf_adae %>%
  count(TRTA, AEDECOD) %>%
  pivot_wider(names_from = TRTA, values_from = n, values_fill = 0) %>%
  mutate(SUBLINEBY = "Study: X") 

cols <- names(tbl)[! names(tbl) %in% c("SUBLINEBY")]

head(tbl) %>%
  rtf_page(
    margin = c(1.75, 1.75, 1.0, 1.0, 0.5, 0.5),
    col_width = 5) %>%
  rtf_colheader(colheader = paste(cols, collapse = "|"), 
                text_indent_first = -108,
                text_indent_left = -108,
                text_indent_right = -108
                ) %>%
  rtf_body(text_indent_first = -108, 
           text_indent_left = -108,
           text_indent_right = -108,
           subline_by = "SUBLINEBY") %>% 
  rtf_encode() %>% 
  write_rtf("intro-ae1.rtf") 
```

![image](https://user-images.githubusercontent.com/16843423/146591750-60f184b8-ef4d-4f43-bf95-7385734506c1.png)

**Comment by elong0527** [comment]
`r2rtf` allow vectorized input. As `SUBLINE` is a variable, you can control its layout by providing a vector as input for `text_indent_xxx`. 

For example:

```
library(r2rtf)
library(dplyr)
library(tidyr)

tbl <- r2rtf_adae %>%
  count(TRTA, AEDECOD) %>%
  pivot_wider(names_from = TRTA, values_from = n, values_fill = 0) %>%
  mutate(SUBLINEBY = "Study: X") 

cols <- names(tbl)[! names(tbl) %in% c("SUBLINEBY")]

head(tbl) %>%
  rtf_page(
    margin = c(1.75, 1.75, 1.0, 1.0, 0.5, 0.5),
    col_width = 5) %>%
  rtf_colheader(colheader = paste(cols, collapse = "|"), 
                text_indent_first = -108,
                text_indent_left = -108,
                text_indent_right = -108
  ) %>%
  rtf_body(text_indent_first = c(rep(-108, 4), 0), 
           text_indent_left = c(rep(-108, 4), 0),
           text_indent_right = c(rep(-108, 4), 0),
           subline_by = "SUBLINEBY") %>% 
  rtf_encode() %>% 
  write_rtf("intro-ae1.rtf") 
```

**Comment by tdwils** [comment]
That works. Thank you very much!

**Comment by dnirajan** [comment]
Hi @elong0527 text_indent_xxx arguments with a negative value are applied only on the first line. If we have a long string then text_indent_xxx is not applied. How to apply this on second line too?

library(r2rtf)
library(dplyr)
library(tidyr)

data <- r2rtf_adae %>% 
  mutate(
    AEDECOD = paste0(AEDECOD, "New Line New Line")
  )

tbl <- data %>%
  count(TRTA, AEDECOD) %>%
  pivot_wider(names_from = TRTA, values_from = n, values_fill = 0) %>%
  mutate(SUBLINEBY = "Study: X") 

cols <- names(tbl)[! names(tbl) %in% c("SUBLINEBY")]

head(tbl) %>%
  rtf_page(
    margin = c(1.75, 1.75, 1.0, 1.0, 0.5, 0.5),
    col_width = 5) %>%
  rtf_colheader(colheader = paste(cols, collapse = "|"), 
                text_indent_first = -45,
                text_indent_left = -45,
                text_indent_right = -45
  ) %>%
  rtf_body(text_indent_first = c(rep(-45, 4), 0), 
           text_indent_left = c(rep(-45, 4), 0),
           text_indent_right = c(rep(-45, 4), 0),
           text_justification = c(rep("l",4)),
           subline_by = "SUBLINEBY") %>% 
  rtf_encode() %>% 
  write_rtf("data/para-indent.rtf") 

and the output is:
![indent](https://github.com/Merck/r2rtf/assets/58128009/3d02ea03-fa84-4030-b164-5e2a64299b94)

**Comment by elong0527** [comment]
Set `text_indent_first = 0` in all places. The value is relative to `text_indent_left`.

**Comment by dnirajan** [comment]
HI @elong0527 
The problem is I need to change the table cell margin from 0.08 to 0.01. However, as discussed above, I don't have direct access to modify the cell margin. (the value 108 is hard-coding and you did not expect the user to modify them).
I attempted using negative indentation through text_indent_xxx but encountered a problem. Initially, the text is left-indented at text_indent_left = -45, but upon a line break, it resets to text_indent_left = 0.

library(r2rtf)
library(dplyr)
library(tidyr)

tbl <- r2rtf_adae %>%
  select(AEBODSYS,USUBJID, TRTA, AEDECOD) %>% 
  head()

tbl %>%
  rtf_page(
    margin = c(1.75, 1.75, 1.0, 1.0, 0.5, 0.5),
    col_width = 5
  ) %>%
  rtf_colheader(
    colheader = paste(names(tbl), collapse = "|"),
    text_indent_first = -45,
    text_indent_left = -45,
    text_indent_right = -45,
    text_justification = "l"
  ) %>%
  rtf_body(
    text_indent_first = c(rep(-45, 4)),
    text_indent_left = c(rep(-45, 4)),
    text_indent_right = c(rep(-45, 4)),
    text_justification = "l"
  ) %>%
  rtf_encode() %>%
  write_rtf("/para-indent.rtf")

![image](https://github.com/Merck/r2rtf/assets/58128009/2a2f3d53-daab-4f4d-bf7c-3dcc0626ee8b)

Again, as suggested, I used text_indent_first = 0 in all places then all the text inside the table starts from text_indent_left = 0 but I used text_indent_left = -45. The text needs to have indentation text_indent_left = -45 but resets to text_indent_left = 0. Is there a solution for this?

library(r2rtf)
library(dplyr)
library(tidyr)

tbl <- r2rtf_adae %>%
  select(AEBODSYS,USUBJID, TRTA, AEDECOD) %>% 
  head()

tbl %>%
  rtf_page(
    margin = c(1.75, 1.75, 1.0, 1.0, 0.5, 0.5),
    col_width = 5
  ) %>%
  rtf_colheader(
    colheader = paste(names(tbl), collapse = "|"),
    text_indent_first = 0,
    text_indent_left = -45,
    text_indent_right = -45,
    text_justification = "l"
  ) %>%
  rtf_body(
    text_indent_first = c(rep(0, 4)),
    text_indent_left = c(rep(-45, 4)),
    text_indent_right = c(rep(-45, 4)),
    text_justification = "l"
  ) %>%
  rtf_encode() %>%
  write_rtf("/para-indent.rtf")
  
![image](https://github.com/Merck/r2rtf/assets/58128009/9053784a-3b4d-40ab-ba05-dc9df315f1e5)
In this figure, there is a space of 0.08 between the table border and the texts.

The output I need is:
![image](https://github.com/Merck/r2rtf/assets/58128009/4a8ed1fb-ed73-47e0-98bb-e446eb9e4e79)

**Comment by elong0527** [comment]
Here is the code to get the output. 

```
library(r2rtf)
library(dplyr)
library(tidyr)

tbl <- r2rtf_adae %>%
  count(TRTA, AEDECOD) %>%
  pivot_wider(names_from = TRTA, values_from = n, values_fill = 0)

head(tbl) %>%
  rtf_page(col_width = 5) %>%
  rtf_colheader(
    text_justification = "l",
    colheader = paste(names(tbl), collapse = "|"), 
    text_indent_first = 0,
    text_indent_left = -108,
    text_indent_right = -108) %>%
  rtf_body(
    text_justification = "l",
    text_indent_first = 0, 
    text_indent_left = -108, 
    text_indent_right = -108) %>% 
  rtf_encode() %>% 
  write_rtf("intro-ae1.rtf") 
```

**Comment by dnirajan** [comment]
The above code solves my problem. Thank you very much @elong0527
