### ISSUE TITLE
rtf_footnote with text_justification = "l" and as_table = FALSE indents the line 1/4 inch

### ISSUE THREAD

**Issue by Robert-Krajcik** [Merck/r2rtf#8]
I have a reproducible example for you:

```{r, eval = FALSE}
library(dplyr)
library(stringr)
library(r2rtf)

# create mtcars2 from mtcars
data(mtcars)
mtcars2 <- mtcars %>% 
  mutate(carname = rownames(mtcars)) %>% 
  arrange(wt) %>% 
  select(carname,mpg,cyl,disp,hp,wt,am,gear)
  
rel_wd <- c(2.5, rep(1.0,4), 1.5, 1, 1)

# setup column headers
hdrs <- paste(colnames(mtcars2), collapse = "|")

# source line
reptname <- "l-mtcars-reprex.rtf"
date_str <- paste0("DATE: ",toupper(format(Sys.Date(), format="%d%b%Y")))
npad <- 102 - sum(nchar("SOURCE: "),nchar(reptname),nchar(date_str))
splitstr <- paste0("\n","SOURCE: ",reptname,str_pad(" ",npad),date_str)

cmb_rtf <- mtcars2 %>%
  rtf_page(orientation = "landscape", 
           border_first = "single", border_last = "single",
           margin = c(1.0, 1.0, 1.25, 1.25, 0.5, 0.5), 
           nrow = 24) %>% 
  
  rtf_title(title = "Listing of mtcars data, sorted by weight",
            subtitle = "Page \\pagenumber of \\totalpage",
            text_font_size = 10, text_font = 9, text_convert = TRUE) %>%
  
  rtf_colheader(colheader = hdrs,
                border_left = "", border_right = "", 
                text_font_size = 10, text_font = 9, # 9 = Courier New
                text_space_before = 60, text_space_after = 60,
                col_rel_width = rel_wd,
                cell_justification = "l",
                text_justification =  c("l",rep(c("d","r"),3),"r") ) %>% 

  rtf_body(col_rel_width = rel_wd,
           text_space = 1,
           text_space_before = 0,
           text_space_after = 120,
           cell_justification =  "l",
           text_justification =  c("l",rep(c("d","r"),3),"r"),
           text_font_size = 10, text_font = 9,
           border_left = "", border_right = "") %>% 
  
  rtf_footnote(footnote = "[1] This is a footnote.",
               text_font_size = 10, text_font = 9,
               text_justification = "l",
               cell_justification = "l",
               border_left = "", border_right = "",
               as_table = FALSE) %>%
  
  rtf_source(source = splitstr,
             text_justification = "j",text_font_size = 10, text_font = 9, text_convert = TRUE)

cmb_rtf %>% 
  rtf_encode() %>%
  write_rtf(reptname)
```
Opening the output in Notepad++

`{\pard\hyphpar
\sb15\sa15\fi0\li360\ri0\ql
{\f8\fs20 [1] This is a footnote.}
\par}`

the \li360 indents 360 twips, 1/4 inch. -- I think it should be \li0

Thanks

**Comment by elong0527** [comment]
The current default is to align the footnote with the table border instead of page margin. 

So it is `\li0` but `\li360`.

**Comment by Robert-Krajcik** [comment]
So if I use `as_table = TRUE` then I get \li0 and it perfectly left-aligns?
Or is there some other alignment option I hadn't read?
I went through your vignettes and the PharmaSUG paper but didn't see them.

**Comment by elong0527** [comment]
It is a new feature we implemented after we wrote the paper. 

`as_table` controls if the footnote/data source is within or outside of the table body. 

left-alignment is defined as align with the left border of the table in `r2rtf`.  (I shall discuss it in Vignette)

Could you show me a screenshot of the table you want to achieve? I can think if it is already available in `r2rtf`.

**Comment by Robert-Krajcik** [comment]
Actually this looks fine here.  
Using `as_table = TRUE` and setting `border_bottom = ""` to remove the line between the footnote and the source line.
So I don't need anything else at the moment.  Thanks for your time!
![image](https://user-images.githubusercontent.com/75215958/101502692-3cc1f880-393f-11eb-89bb-e806db7d2e3a.png)

**Comment by elong0527** [comment]
Cool!

**Comment by nielsonc** [comment]
Is there also a way to make the footnote appear on multi-page figure files? Adding as_table=TRUE in rtf_footnote() doesn't seem to accomplish that (maybe since I don't have tables -- just PNGs).

**Comment by elong0527** [comment]
Please refer #9 , there are arguments in ‘rtf_encode’ to control the appearance of footnote data source in each page.  It shall applied to both table and figure.
