### ISSUE TITLE
Total page number not displaying correctly when multiple pages are combined

### ISSUE THREAD

**Issue by tdwils** [Merck/r2rtf#83]
We are creating a table with one subject per page using the method of issue #80 (creating one subject per file, and then combining the files), and we want to put the page number (Page X of Y) in the `rtf_title()`. But the total page number (`\\totalpage`) in the title starts over at each Subject ID. The page numbering in the `rtf_page_header()` works correctly. 

How can we have the page numbering in the title work like the page numbering in the page header (1 of 3, 2 of 3, 3 of 3)?

Sample code:

```
library(r2rtf)
library(dplyr)


data(r2rtf_adae)

ae_t1 <- r2rtf_adae %>%
  filter(USUBJID %in% c("01-701-1383", "01-701-1444")) %>%
  mutate(SUBLINEBY = TRTA) %>%   
  select(USUBJID, ASTDY, AEDECOD, SUBLINEBY) 

# split data by USUBJID
x <- split(ae_t1, ae_t1$USUBJID)

# create one AE listing file per subject.
x_encode <- lapply(x, function(tbl){
  
  tbl %>%
    arrange(SUBLINEBY, USUBJID, ASTDY) %>%
    rtf_page(orientation = "landscape", nrow = 15) %>%
    rtf_page_header() %>%
    rtf_title(c("AE Listing", 
                "Page \\pagenumber of \\totalpage")) %>%
    rtf_body( 
      subline_by = "SUBLINEBY",
      group_by = c("USUBJID", "ASTDY")) %>% 
    rtf_encode()
  
})

# Combine other RTF body to the first one  
x_encode[[1]]$body <- paste(lapply(x_encode, function(x) x$body), collapse = r2rtf:::as_rtf_new_page())

x_encode[[1]] %>% write_rtf("output.rtf")
```

The page numbering in the page header is correct, but the total page number in the title is not correct:

![image](https://user-images.githubusercontent.com/16843423/146792217-d3815316-272c-4864-9f55-4cc8279a3f76.png)

**Comment by elong0527** [comment]
`\\totalpage` is a pre-calculated number in R code. 

If you need to combine multiple files, you would need to calculate it in R and then put it in the title.

**Comment by tdwils** [comment]
Thank you for the clarification.

I have implemented a variation of the function from #6 to calculate the total number of pages after the RTF document has been processed. Below is my solution for reference. I think we can close this now. Thank you!

```
library(r2rtf)
library(dplyr)


data(r2rtf_adae)

ae_t1 <- r2rtf_adae %>%
  filter(USUBJID %in% c("01-701-1383", "01-701-1444")) %>%
  mutate(SUBLINEBY = TRTA) %>%   
  select(USUBJID, ASTDY, AEDECOD, SUBLINEBY) 

# split data by USUBJID
x <- split(ae_t1, ae_t1$USUBJID)


# create one AE listing file per subject.
x_encode <- lapply(x, function(tbl){
  
  tbl %>%
    arrange(SUBLINEBY, USUBJID, ASTDY) %>%
    rtf_page(orientation = "landscape", nrow = 15) %>%
    rtf_page_header() %>%
    rtf_title(c("AE Listing", 
                "Page \\pagenumber of totalnumpages")) %>%
    rtf_body( 
      subline_by = "SUBLINEBY",
      group_by = c("USUBJID", "ASTDY")) %>% 
    rtf_encode()
  
})

# Combine other RTF body to the first one  
x_encode[[1]]$body <- paste(lapply(x_encode, function(x) x$body), collapse = r2rtf:::as_rtf_new_page())

# Insert total number of pages
totalpages <- function(rtf_doc, string = "totalnumpages") {
  # Replaces "string" with the total number of pages in RTF document body
  
  pages <- gregexpr("\\\\page", rtf_doc$body)  # \page = Required page break
  NumPages <- length(pages[[1]]) + 1
  
  rtf_doc$body <- gsub(string, as.character(NumPages), rtf_doc$body)
  
  return(rtf_doc)
}

x_encode[[1]] <- totalpages(x_encode[[1]], string = "totalnumpages")

x_encode[[1]] %>% write_rtf("output.rtf")
```

**Comment by Jianminlong** [comment]
2 comments about the above program: 

1) About clinical application of one subject per table/listing/file.  If this is something like to generate report cards for students, then it makes sense to have page numbering for each student's report card.  If one has a report card with 3 pages, then it would be labeled as page 1 of 3, 2 of 3 and 3 of 3 for that student.  And do the same for other students.  The total number of page is not very relevant in this case.  

2) The program works for a nicer data like this one from CDISC, but it will break for some other difficult data.  So see this, I just added a line of code after ` rtf_body(col_rel_width = c(3, 3, 1),  ` to simulate some other data.

**Comment by tdwils** [comment]
Thank you for your comments on the code.

For something like a report card, where each document will be issued separately, I agree that per-subject pagination makes sense. For our purposes, we need all subjects in one document, but we want to see one subject per page for display purposes. 

However, for a report card, the parameter `\\pagenumber` is giving the page number in the whole document, not the page number for each subject. That is, it does not start over at 1 for a new subject. So for a report card, that would need to be changed.

Regarding the second point, I added the `col_rel_width` line to the code, and I was able to get it to work by adding a fourth width:

```
rtf_body(col_rel_width = c(3, 3, 3, 1),
      subline_by = "SUBLINEBY",
      group_by = c("USUBJID", "ASTDY")) %>%
```
Please let me know if I am misunderstanding.

**Comment by elong0527** [comment]
Close the issue as the original issue has been addressed.

**Comment by Jianminlong** [comment]
To @tdwils , it was a mistake of mine, while I tried to adjust the relative ratio of widths on the header row, and I got a strange output and I didn't realized that it was my fault. I jumped the gun a little bit and I'm sorry for that.  The program works in the current form. 
To @elong0527 , not sure we know how much stress test was done on r2rtf, and not sure if any documented limitations of r2rtf have.  The point of whole exercise above is to take the page numbering out the header area and make one subject per page, and this only happens in the highly regulated clinical trial documents, since the regulatory publishing wants to reserve that area for their use.   IF r2rtf's only goal is to serve this purpose, this should be mentioned somewhere in the r2rtf documentation.   We kind of know that the Merck's SAS macro %RTFTable serves that purpose and it doesn't have to say it in any documentation, since it's only  purpose is to support the work of the Company.   r2rtf might be different now and it has a much wider audience?
Merry Christmas and Happy New Year!

**Comment by elong0527** [comment]
Thanks for the clarification. As the topic is different, you may consider to open another issue if necessary. 

`r2rtf` is a general purpose R package. The goal is to simplify R user to create TLFs in RTF format. 

All testing cases are in https://github.com/Merck/r2rtf/tree/master/tests/testthat with a summary in https://app.codecov.io/gh/Merck/r2rtf?branch=master
