### ISSUE TITLE
rtf_footnote doesn't repeat across pages like rtf_title

### ISSUE THREAD

**Issue by Robert-Krajcik** [Merck/r2rtf#9]
Refer to the reprex in issue #8

Any chance to get the footnotes to repeat across pages, like the titles and colheaders do?

Thanks,
Robert

**Comment by elong0527** [comment]
It is actually been handled in `rtf_encode` after setting ` page_footnote = "all"`

https://merck.github.io/r2rtf/reference/rtf_encode.html

**Comment by Robert-Krajcik** [comment]
I hadn't seen this before.  
Thanks Yilong, it worked!
