### ISSUE TITLE
rft_encode() doesn't add footnote and source to all pages for doc_type = "figure"

### ISSUE THREAD

**Issue by Raylight07** [Merck/r2rtf#90]
Hi @elong0527,

I ran the following code. But footnote and source doesn't appear in each pages. 

`
library(dplyr)   # version '1.0.8'
library(ggplot2) # version ‘3.3.5’
library(r2rtf)   # version ‘0.3.2’ 

for(i in sort(unique(iris$Species))) {
  fil_data <-  iris %>% filter(Species == i) 
  
  p <- ggplot2::ggplot(fil_data, aes(x = Sepal.Length, y = Sepal.Width))+
    geom_point(size = 3)+
    theme_minimal()
  
  plot_file <- paste0("figure_", i, ".png") 
  
  ggplot2::ggsave(filename = plot_file, plot = p, 
                  path=file.path(tempdir()), device="png", width=8.9, height=4.5, units = "in")
}

filename <- file.path(tempdir(), purrr::map_chr(unique(iris$Species),
                                                ~ paste0("figure_", .x, ".png")))

ttl1 <- "Plot of iris Sepal.Width by Sepal.Length"
ttl2 <- paste([\\b0\\fs20](file://b0/fs20),"Page [\\pagenumber](file://pagenumber/) of [\\totalpage](file://totalpage/)")

## Create RTF file
fig_rtf <- filename %>%
  rtf_read_png() %>%                      # read PNG files from the file path
  rtf_title(ttl1, ttl2) %>%                  # add title or subtitle
  rtf_figure() %>%                 
  rtf_footnote("footnote", text_justification = "l" ) %>%     # add footnote
  rtf_source("[source: IRIS data]", text_justification = "l") # add data source

fig_rtf %>%
  rtf_encode(page_footnote = "all",
             page_source = "all",
             doc_type = "figure") %>%
  write_rtf(file = file.path(getwd(),"/","iris_3specices.rtf"))
[iris_3specices.pdf](https://github.com/Merck/r2rtf/files/8188323/iris_3specices.pdf)
`

**Comment by elong0527** [comment]
Thanks! The bug is fixed in https://github.com/Merck/r2rtf/commit/c41fd4bf1680ad3d523cea70f3dff10d6e170ba7
