### ISSUE TITLE
Could you someone check if there is an issue in the utf8Tortf function?

### ISSUE THREAD

**Issue by Mr-ZBin** [Merck/r2rtf#93]
Hi,

When I tried to convert "中文脚注" to rtf code, the "脚" is not correct because there are two "-" in the rtf code. So I changed the function as below and it works well now. Could you someone check this issue?

utf8Tortf <- function(text) {
  stopifnot(length(text) == 1 & "character" %in% class(text))

  x_char <- unlist(strsplit(text, ""))
  x_int <- utf8ToInt(text)
  x_rtf <- ifelse(x_int <= 255, x_char,
    ifelse(x_int <= 32768, paste0("\\uc1\\u", x_int, "?"),
      paste0("\\uc1\\u", x_int - 65536, "?")
    )
  )

  paste0(x_rtf, collapse = "")
}

Thanks,
Bin

**Comment by meeeeeeeeo** [comment]
I find the same problem,

The rtf code of `'试'` should be `"\\uc1\\u-29739?"`, but now `r2rtf:::utf8Tortf` convert it to `"\\uc1\\u--29739?"`, with a additional `-`.

**Comment by elong0527** [comment]
Fixed in https://github.com/Merck/r2rtf/commit/4f0031e809b1c0647aabf8045d81a7dda11dd6cf

I also exported this function. Could you share example code on using `utf8Tortf`? 

It can help me improve the support for CJK character. Thanks!

**Comment by elong0527** [comment]
Please also refer #94, if anyone is interested, please consider to contribute a translation of the `r2rtf.Rmd` file in Chinese.

**Comment by nanxstats** [comment]
Can this issue be closed?
